# add_data.py

import os
import django

# Djangoの設定を読み込む
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'favorite_vtuber_project.settings')
django.setup()

# データ追加に必要なモデルをインポート
from favorite_vtuber_app.models import MVtubers, MVtuberTags

# データ追加の処理を記述
def add_data2():
    # VTuber情報
    MVtubers.objects.bulk_create([
        # MVtubers(
        #     id=1,
        #     office_id=1,
        #     name_ja='ときのそら',
        #     name_en='Tokino Sora',
        #     tag1=MVtuberTags.objects.get(id=1),
        #     tag2=None,
        #     image_filename='h1.png',
        #     thumbnail_filename='h1_t.png',
        #     catch_text='「そらとものみんなー！元気ー？ときのそらです！」',
        #     introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/0_そら.mp4',
        #     youtube_url='https://www.youtube.com/channel/UCp6993wxpyDPHUpavwDFqgg?sub_confirmation=1',
        #     twitter_url='https://twitter.com/tokino_sora',
        #     recommended_video1='https://www.youtube.com/watch?v=NT6Pf28eCgQ',
        #     recommended_video2='https://www.youtube.com/watch?v=ZXF1SzAtFj8',
        #     recommended_video3='https://www.youtube.com/watch?v=LPEE4MMDieo'
        # ),
        MVtubers(
            id=2,
            office_id=1,
            name_ja='ロボ子さん',
            name_en='Robocosan',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h2.png',
            thumbnail_filename='h2_t.png',
            catch_text='「はろーぼー！ロボ子だよー」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2023/06/little-bit.mp4',
            youtube_url='https://www.youtube.com/channel/UCDqI2jOz0weumE8s7paEk6g?sub_confirmation=1',
            twitter_url='https://twitter.com/robocosan',
            recommended_video1='https://www.youtube.com/watch?v=K8n-pGOrpzc',
            recommended_video2='https://www.youtube.com/watch?v=inHAAbWA3Jk',
            recommended_video3='https://www.youtube.com/watch?v=_WuSd5M7va4'
        ),
        MVtubers(
            id=3,
            office_id=1,
            name_ja='AZKi',
            name_en=None,
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h3.png',
            thumbnail_filename='h3_t.png',
            catch_text='「Virtual Diva AZKi 仮想世界の歌姫！音楽と歌うことが大好き！」',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UC0TXe_LYZ4scaW2XMyi5_kw?sub_confirmation=1',
            twitter_url='https://twitter.com/AZKi_VDiVA',
            recommended_video1='https://www.youtube.com/watch?v=IsTij69xLBc',
            recommended_video2='https://www.youtube.com/watch?v=z7EC1VM9L-U',
            recommended_video3='https://www.youtube.com/watch?v=JaTS4xhV7b8'
        ),
        MVtubers(
            id=4,
            office_id=1,
            name_ja='さくらみこ',
            name_en='Sakura Miko',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h4.png',
            thumbnail_filename='h4_t.png',
            catch_text='「にゃっはろ～！ホロライブ所属のエリート巫女アイドルさくらみこですっ！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/04/gif%E5%8B%95%E7%94%BB.gif',
            youtube_url='https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA?sub_confirmation=1',
            twitter_url='https://twitter.com/sakuramiko35',
            recommended_video1='https://www.youtube.com/watch?v=X9zw0QF12Kc',
            recommended_video2='https://www.youtube.com/watch?v=HiLnCY9qjSo',
            recommended_video3='https://www.youtube.com/watch?v=P3kv98KtlFg'
        ),
        MVtubers(
            id=5,
            office_id=1,
            name_ja='星街すいせい',
            name_en='Hoshimachi Suisei',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h5.png',
            thumbnail_filename='h5_t.png',
            catch_text='「彗星の如く現れたスターの原石！アイドルVTuberの星街すいせいです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/0_すいせい.mp4',
            youtube_url='https://www.youtube.com/channel/UC5CwaMl1eIgY8h02uZw7u8A?sub_confirmation=1',
            twitter_url='https://twitter.com/suisei_hosimati',
            recommended_video1='https://www.youtube.com/watch?v=zLak0dxBKpM',
            recommended_video2='https://www.youtube.com/watch?v=vQHVGXdcqEQ',
            recommended_video3='https://www.youtube.com/watch?v=ZfDYRy17CBY'
        ),
        MVtubers(
            id=6,
            office_id=1,
            name_ja='アキ・ローゼンタール',
            name_en='Aki Rosenthal',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=None,
            image_filename='h6.png',
            thumbnail_filename='h6_t.png',
            catch_text='「アローナ！癒し系ハーフエルフお姉さん、アキロゼと一緒に乾杯しよ？」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/04/GIF本完成.gif',
            youtube_url='https://www.youtube.com/channel/UCFTLzh12_nrtzqBPsTCqenA?sub_confirmation=1',
            twitter_url='https://twitter.com/akirosenthal',
            recommended_video1='https://www.youtube.com/watch?v=Ii7rtNaGlls',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=7,
            office_id=1,
            name_ja='赤井はあと',
            name_en='Akai Haato',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=None,
            image_filename='h7.png',
            thumbnail_filename='h7_t.png',
            catch_text='「こんるーじゅ！赤井はあとよ！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/1_はあと.mp4',
            youtube_url='https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg?sub_confirmation=1',
            twitter_url='https://twitter.com/akaihaato',
            recommended_video1='https://www.youtube.com/watch?v=zXzsdzFR4BA',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=8,
            office_id=1,
            name_ja='白上フブキ',
            name_en='Shirakami Fubuki',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=MVtuberTags.objects.get(id=4),
            image_filename='h8.png',
            thumbnail_filename='h8_t.png',
            catch_text='「こんこんきーつね！白上フブキです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/1_フブキ.mp4',
            youtube_url='https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg?sub_confirmation=1',
            twitter_url='https://twitter.com/shirakamifubuki',
            recommended_video1='https://www.youtube.com/watch?v=eO1jo_onIEg',
            recommended_video2='https://www.youtube.com/watch?v=qvIZWqp-TMY',
            recommended_video3=None
        ),
        MVtubers(
            id=9,
            office_id=1,
            name_ja='夏色まつり',
            name_en='Natsuiro Matsuri',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=None,
            image_filename='h9.png',
            thumbnail_filename='h9_t.png',
            catch_text='「わっしょ～い！ホロライブの清楚担当みんなのアイドル夏色まつりです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/1_まつり.mp4',
            youtube_url='https://youtube.com/channel/UCQ0UDLQCjY0rmuxCDE38FGg?sub_confirmation=1',
            twitter_url='https://twitter.com/natsuiromatsuri',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=10,
            office_id=1,
            name_ja='湊あくあ',
            name_en='Minato Aqua',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h10.png',
            thumbnail_filename='h10_t.png',
            catch_text='「皆さんどうもこんあくあ～！バーチャルアイドル ゲーマー猫耳メイドの湊あくあで～す！！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/2_あくあ.mp4',
            youtube_url='https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg?sub_confirmation=1',
            twitter_url='https://twitter.com/minatoaqua',
            recommended_video1='https://www.youtube.com/watch?v=6bnaBnd4kyU',
            recommended_video2='https://www.youtube.com/watch?v=O8v5S1nhKzo',
            recommended_video3='https://www.youtube.com/watch?v=aGlY6Ueaco0'
        ),
        MVtubers(
            id=11,
            office_id=1,
            name_ja='紫咲シオン',
            name_en='Murasaki Shion',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h11.png',
            thumbnail_filename='h11_t.png',
            catch_text='「こんしお～、紫咲シオンだよ」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/10/829524_727810.gif',
            youtube_url='https://www.youtube.com/channel/UCXTpFs_3PqI41qX2d9tL2Rw?sub_confirmation=1',
            twitter_url='https://twitter.com/murasakishionch',
            recommended_video1='https://www.youtube.com/watch?v=OZmYNcs7-wo',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=12,
            office_id=1,
            name_ja='百鬼あやめ',
            name_en='Nakiri Ayame',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h12.png',
            thumbnail_filename='h12_t.png',
            catch_text='「人間様たちこんなきりー！やほ～～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/2_あやめ.mp4',
            youtube_url='https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg?sub_confirmation=1',
            twitter_url='https://twitter.com/nakiriayame',
            recommended_video1='https://www.youtube.com/watch?v=ClrzryIkpTA',
            recommended_video2='https://www.youtube.com/watch?v=jHd7SPreuAQ',
            recommended_video3='https://www.youtube.com/watch?v=c9VYairGvn4?t=1078'
        ),
        MVtubers(
            id=13,
            office_id=1,
            name_ja='癒月ちょこ',
            name_en='Yuzuki Choco',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h13.png',
            thumbnail_filename='h13_t.png',
            catch_text='「Good evening!my cute students.ちょっこーん！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/10/366159_806304.gif',
            youtube_url='https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg?sub_confirmation=1',
            twitter_url='https://twitter.com/yuzukichococh',
            recommended_video1='https://www.youtube.com/watch?v=n9DqvVNBdVI',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=14,
            office_id=1,
            name_ja='大空スバル',
            name_en='Oozora Subaru',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h14.png',
            thumbnail_filename='h14_t.png',
            catch_text='「ちわーす！ホロライブ2期生大空スバルっス！！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/04/GIF.gif',
            youtube_url='https://www.youtube.com/channel/UCvzGlP9oQwU--Y0r9id_jnA?sub_confirmation=1',
            twitter_url='https://twitter.com/oozorasubaru',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=15,
            office_id=1,
            name_ja='大神ミオ',
            name_en='Ookami Mio',
            tag1=MVtuberTags.objects.get(id=4),
            tag2=None,
            image_filename='h15.png',
            thumbnail_filename='h15_t.png',
            catch_text='「こんばんみぉーん！大神ミオだよ～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/g_ミオ.mp4',
            youtube_url='https://www.youtube.com/channel/UCp-5t9SrOQwXMU7iIjQfARg?sub_confirmation=1',
            twitter_url='https://twitter.com/ookamimio',
            recommended_video1='https://www.youtube.com/watch?v=XoaUBfmG8Ow',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=16,
            office_id=1,
            name_ja='猫又おかゆ',
            name_en='Nekomata Okayu',
            tag1=MVtuberTags.objects.get(id=4),
            tag2=None,
            image_filename='h16.png',
            thumbnail_filename='h16_t.png',
            catch_text='「もぐもぐ～おかゆ～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2024/04/Nekomata-Okayu_movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCvaTdHTWBGv3MKj3KVqJVCw?sub_confirmation=1',
            twitter_url='https://twitter.com/nekomataokayu',
            recommended_video1='https://www.youtube.com/watch?v=P9auWa9ON1o',
            recommended_video2='https://www.youtube.com/watch?v=G_L6m4Ww1DI',
            recommended_video3='https://www.youtube.com/watch?v=IHkPvsE5gUI'
        ),
        MVtubers(
            id=17,
            office_id=1,
            name_ja='戌神ころね',
            name_en='Inugami Korone',
            tag1=MVtuberTags.objects.get(id=4),
            tag2=None,
            image_filename='h17.png',
            thumbnail_filename='h17_t.png',
            catch_text='「ぉぁよ～！ゆびゆび～」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/10/368714_768061.gif',
            youtube_url='https://www.youtube.com/channel/UChAnqc_AY5_I3Px5dig3X1Q?sub_confirmation=1',
            twitter_url='https://twitter.com/inugamikorone',
            recommended_video1='https://www.youtube.com/watch?v=I9m2C_Vx1j4',
            recommended_video2='https://www.youtube.com/watch?v=5wCvCFEUzmc',
            recommended_video3=None
        ),
        MVtubers(
            id=18,
            office_id=1,
            name_ja='兎田ぺこら',
            name_en='Usada Pekora',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h18.png',
            thumbnail_filename='h18_t.png',
            catch_text='「こんぺこ！こんぺこ！こんぺこー！兎田ぺこらぺこ～！どうも〜どうも〜」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/3_ぺこら.mp4',
            youtube_url='https://www.youtube.com/channel/UC1DCedRgGHBdm81E1llLhOQ?sub_confirmation=1',
            twitter_url='https://twitter.com/usadapekora',
            recommended_video1='https://www.youtube.com/watch?v=7k-r7P9TXdQ',
            recommended_video2='https://www.youtube.com/watch?v=yy8asHUr9vQ',
            recommended_video3='https://www.youtube.com/watch?v=AAr2lHZLNyU'
        ),
        MVtubers(
            id=19,
            office_id=1,
            name_ja='不知火フレア',
            name_en='Shiranui Flare',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h19.png',
            thumbnail_filename='h19_t.png',
            catch_text='「こんぬいー！ホロライブ3期生の不知火フレアだよ！」',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UCvInZx9h3jC2JzsIzoOebWg?sub_confirmation=1',
            twitter_url='https://twitter.com/shiranuiflare',
            recommended_video1='https://www.youtube.com/watch?v=3y8oIuEkqQs',
            recommended_video2='https://www.youtube.com/watch?v=ogiRp9DaSP8',
            recommended_video3='https://www.youtube.com/watch?v=ZMlPAsIJslA&t=2743s'
        ),
        MVtubers(
            id=20,
            office_id=1,
            name_ja='白銀ノエル',
            name_en='Shirogane Noel',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h20.png',
            thumbnail_filename='h20_t.png',
            catch_text='「こんまっする～！鉄の胃袋大魔神！ 白銀聖騎士団の団長、白銀ノエルです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/07/MOVIE.mp4',
            youtube_url='https://www.youtube.com/channel/UCdyqAaZDKHXg4Ahi7VENThQ?sub_confirmation=1',
            twitter_url='https://twitter.com/shiroganenoel',
            recommended_video1='https://www.youtube.com/watch?v=Pt4GlDfYwa0',
            recommended_video2='https://www.youtube.com/watch?v=_gb44X05LsU',
            recommended_video3=None
        ),
        MVtubers(
            id=21,
            office_id=1,
            name_ja='宝鐘マリン',
            name_en='Houshou Marine',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h21.png',
            thumbnail_filename='h21_t.png',
            catch_text='「Ahoy!宝鐘海賊団船長！宝鐘マリンです～！」「ヨーソロー」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2023/03/Houshou-Marine_megane_movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCCzUftO8KOVkV4wQG1vkUvg?sub_confirmation=1',
            twitter_url='https://twitter.com/houshoumarine',
            recommended_video1='https://www.youtube.com/watch?v=3LaDuoHDC_g',
            recommended_video2='https://www.youtube.com/watch?v=WSDkNw2c4A8',
            recommended_video3='https://www.youtube.com/watch?v=Ry0lMtQQEHI'
        ),
        MVtubers(
            id=22,
            office_id=1,
            name_ja='天音かなた',
            name_en='Amane Kanata',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h22.png',
            thumbnail_filename='h22_t.png',
            catch_text='「へい！みんなこんかなた～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2023/04/Amane-Kanata_pr-movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCZlDXzGoo7d44bwdNObFacg?sub_confirmation=1',
            twitter_url='https://twitter.com/amanekanatach',
            recommended_video1='https://www.youtube.com/watch?v=szUbg1Yar5c',
            recommended_video2='https://www.youtube.com/watch?v=c5czz3xhwTw',
            recommended_video3='https://www.youtube.com/watch?v=FOjfhbv-t6k'
        ),
        MVtubers(
            id=23,
            office_id=1,
            name_ja='角巻わため',
            name_en='Tsunomaki Watame',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h23.png',
            thumbnail_filename='h23_t.png',
            catch_text='「こんばんドドド～！」「わためは悪くないよねぇ？」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/03/210328_角巻わため_GIF.gif',
            youtube_url='https://www.youtube.com/channel/UCqm3BQLlJfvkTsX_hvm0UmA?sub=confirmation=1',
            twitter_url='https://twitter.com/tsunomakiwatame',
            recommended_video1='https://www.youtube.com/watch?v=DGun2cWbPEM',
            recommended_video2='https://www.youtube.com/watch?v=j5n1zqsvfXo',
            recommended_video3='https://www.youtube.com/watch?v=TgiT1DQe_io&t=1977s'
        ),
        MVtubers(
            id=24,
            office_id=1,
            name_ja='常闇トワ',
            name_en='Tokoyami Towa',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h24.png',
            thumbnail_filename='h24_t.png',
            catch_text='「こんやっぴーホロライブ4期生常闇トワ様です」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/03/4_トワ_2.mp4',
            youtube_url='https://www.youtube.com/channel/UC1uv2Oq6kNxgATlCiez59hw?sub_confirmation=1',
            twitter_url='https://twitter.com/tokoyamitowa',
            recommended_video1='https://www.youtube.com/watch?v=Ud73fm4Uoq0',
            recommended_video2='https://www.youtube.com/watch?v=Zc05le75CfI',
            recommended_video3='https://www.youtube.com/watch?v=pSg-0zUrbMQ'
        ),
        MVtubers(
            id=25,
            office_id=1,
            name_ja='姫森ルーナ',
            name_en='Himemori Luna',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h25.png',
            thumbnail_filename='h25_t.png',
            catch_text='「みんな～、おりゅ～？」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/09/4_ルーナ-1.mp4-1.mp4',
            youtube_url='https://www.youtube.com/channel/UCa9Y57gfeY0Zro_noHRVrnw?sub_confirmation=1',
            twitter_url='https://twitter.com/himemoriluna',
            recommended_video1='https://www.youtube.com/watch?v=DkGOA3Xhr9s',
            recommended_video2='https://www.youtube.com/watch?v=vlqVuLuZl00',
            recommended_video3='https://www.youtube.com/watch?v=Tf9BTiIHGVw'
        ),
        MVtubers(
            id=26,
            office_id=1,
            name_ja='雪花ラミィ',
            name_en='Yukihana Lamy',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h26.png',
            thumbnail_filename='h26_t.png',
            catch_text='「おはらみです、こんらみです」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/08/lamy_profile_movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCFKOVgVbGmX65RxO3EtH3iw?sub_confirmation=1',
            twitter_url='https://twitter.com/yukihanalamy',
            recommended_video1='https://www.youtube.com/watch?v=wIOrGqv3-RU'
        ),
        MVtubers(
            id=27,
            office_id=1,
            name_ja='桃鈴ねね',
            name_en='Momosuzu Nene',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h27.png',
            thumbnail_filename='h27_t.png',
            catch_text='「こんねね～！ホロライブ5期生オレンジ担当、 アイドルVTuberの桃鈴ねねで～す！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/5_ねね.mp4',
            youtube_url='https://www.youtube.com/channel/UCAWSyEs_Io8MtpY3m-zqILA?sub_confirmation=1',
            twitter_url='https://twitter.com/momosuzunene',
            recommended_video1='https://www.youtube.com/watch?v=YeUkeAq1Dqg?t=290',
            recommended_video2='https://www.youtube.com/watch?v=U0QN3JCHWbw?t=141',
            recommended_video3='https://www.youtube.com/watch?v=K35AflEvvc8'
        ),
        MVtubers(
            id=28,
            office_id=1,
            name_ja='獅白ぼたん',
            name_en='Shishiro Botan',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h28.png',
            thumbnail_filename='h28_t.png',
            catch_text='「ららーいおん♪」「ほならな～」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/5_ぼたん.mp4',
            youtube_url='https://www.youtube.com/channel/UCUKD-uaobj9jiqB-VXt71mA?sub_confirmation=1',
            twitter_url='https://twitter.com/shishirobotan',
            recommended_video1='https://www.youtube.com/watch?v=Lm1k8TI790Y',
            recommended_video2='https://www.youtube.com/watch?v=7zjvFxCetc0?t=86',
            recommended_video3='https://www.youtube.com/watch?v=TNlSd-snAlo?t=104'
        ),
        MVtubers(
            id=29,
            office_id=1,
            name_ja='尾丸ポルカ',
            name_en='Omaru Polka',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h29.png',
            thumbnail_filename='h29_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/5_ぽるか.mp4',
            youtube_url='https://www.youtube.com/channel/UCK9V2B22uJYu3N7eR_BT9QA?sub_confirmation=1',
            twitter_url='https://twitter.com/omarupolka',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=30,
            office_id=1,
            name_ja='ラプラス・ダークネス',
            name_en='La+ Darknesss',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h30.png',
            thumbnail_filename='h30_t.png',
            catch_text='貴様ら、刮目せよ！！',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UCENwRMx5Yh42zWpzURebzTw',
            twitter_url='https://twitter.com/LaplusDarknesss',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=31,
            office_id=1,
            name_ja='鷹嶺ルイ',
            name_en='Takane Lui',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h31.png',
            thumbnail_filename='h31_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_lui.mp4',
            youtube_url='https://www.youtube.com/channel/UCs9_O1tRPMQTHQ-N_L6FU2g',
            twitter_url='https://twitter.com/takanelui',
            recommended_video1='https://www.youtube.com/watch?v=jYWhdr73i6A',
            recommended_video2='https://www.youtube.com/watch?v=O0aSJdN3mVY',
            recommended_video3='https://www.youtube.com/watch?v=5t60NWXXkQI'
        ),
        MVtubers(
            id=32,
            office_id=1,
            name_ja='博衣こより',
            name_en='Hakui Koyori',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h32.png',
            thumbnail_filename='h32_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_koyori.mp4',
            youtube_url='https://www.youtube.com/channel/UC6eWCld0KwmyHFbAqK3V-Rw',
            twitter_url='https://twitter.com/hakuikoyori',
            recommended_video1='https://www.youtube.com/watch?v=7ctmEk_35Yc',
            recommended_video2='https://www.youtube.com/watch?v=Mt5SB2igQUM',
            recommended_video3='https://www.youtube.com/watch?v=PIK13uH30gg'
        ),
        MVtubers(
            id=33,
            office_id=1,
            name_ja='沙花叉クロヱ',
            name_en='Sakamata Chloe',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h33.png',
            thumbnail_filename='h33_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_kuroe.mp4',
            youtube_url='https://www.youtube.com/channel/UCIBY1ollUsauvVi4hW4cumw',
            twitter_url='https://twitter.com/sakamatachloe',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=34,
            office_id=1,
            name_ja='風真いろは',
            name_en='Kazama Iroha',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h34.png',
            thumbnail_filename='h34_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_iroha.mp4',
            youtube_url='https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ',
            twitter_url='https://twitter.com/kazamairohach',
            recommended_video1='https://www.youtube.com/watch?v=ZQveWRj0u5E',
            recommended_video2='https://www.youtube.com/watch?v=au57Syx7wuQ',
            recommended_video3='https://www.youtube.com/watch?v=PIK13uH30gg'
        ),
        MVtubers(
            id=35,
            office_id=1,
            name_ja='火威青',
            name_en='Hiodoshi Ao',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h35.png',
            thumbnail_filename='h35_t.png',
            catch_text='趣味は絵を描くこと。それから仕事は、絵を描くことかな。',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UCMGfV7TVTmHhEErVJg1oHBQ',
            twitter_url='https://twitter.com/hiodoshiao',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=36,
            office_id=1,
            name_ja='音乃瀬奏',
            name_en='Otonose Kanade',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h36.png',
            thumbnail_filename='h36_t.png',
            catch_text='ここが私のステージだから！',
            introduction_video_url=None,
            youtube_url='https://youtube.com/@OtonoseKanade',
            twitter_url='https://twitter.com/otonosekanade',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=37,
            office_id=1,
            name_ja='一条莉々華',
            name_en='Ichijou Ririka',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h37.png',
            thumbnail_filename='h37_t.png',
            catch_text='この一条莉々華に任せておきなさい！',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/@IchijouRirika',
            twitter_url='https://twitter.com/ichijouririka',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=38,
            office_id=1,
            name_ja='儒烏風亭らでん',
            name_en='Juufuutei Raden',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h38.png',
            thumbnail_filename='h38_t.png',
            catch_text='ちょいと一席付き合ってみませんか？',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/@JuufuuteiRaden',
            twitter_url='https://twitter.com/juufuuteiraden',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=39,
            office_id=1,
            name_ja='轟はじめ',
            name_en='Todoroki Hajime',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h39.png',
            thumbnail_filename='h39_t.png',
            catch_text='押忍！なんか、番長っぽくなってきたかも！',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/@TodorokiHajime',
            twitter_url='https://twitter.com/todoroki_hajime',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=40,
            office_id=1,
            name_ja='友人A（えーちゃん）',
            name_en='Friend-A',
            tag1=MVtuberTags.objects.get(id=10),
            tag2=None,
            image_filename='h40.png',
            thumbnail_filename='h40_t.png',
            catch_text='こんにちは、ホロライブスタッフの友人Aです。',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/05/website_achan.mp4',
            youtube_url='https://www.youtube.com/channel/UCJFZiqLMntJufDCHc6bQixg',
            twitter_url='https://twitter.com/achan_UGA',
            recommended_video1='https://www.youtube.com/watch?v=ApKuitWq-TE',
            recommended_video2='https://www.youtube.com/watch?v=fUQALk8Ub2I',
            recommended_video3='https://www.youtube.com/watch?v=fUQALk8Ub2I'
        ),
        MVtubers(
            id=41,
            office_id=1,
            name_ja='春先のどか',
            name_en='Harusaki Nodoka',
            tag1=MVtuberTags.objects.get(id=10),
            tag2=None,
            image_filename='h41.png',
            thumbnail_filename='h41_t.png',
            catch_text='おはようございます！ホロライブ新人スタッフの春先のどかです✨',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/05/website_nodoka.mp4',
            youtube_url='https://www.youtube.com/channel/UCJFZiqLMntJufDCHc6bQixg',
            twitter_url='https://twitter.com/harusakinodoka',
            recommended_video1='https://www.youtube.com/watch?v=ApKuitWq-TE',
            recommended_video2='https://www.youtube.com/watch?v=V1OzY9Z8vqY',
            recommended_video3=None
        ),
    ])

# スクリプトを実行するための条件を設定
if __name__ == '__main__':
    add_data2()
