import os
import django

# Djangoの設定を読み込む
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'favorite_vtuber_project.settings')
django.setup()

# データ追加に必要なモデルをインポート
from favorite_vtuber_app.models import MOffices, MVtuberTags, MVtubers, MVtuberTags, MVtubersProfiles, MFavoriteVideoTags

# データ追加の処理を記述
def add_data():
    # VTuber事務所の追加
    MOffices.objects.create(id=1, office_name='ホロライブ')

    # VTuberタグの追加
    MVtuberTags.objects.bulk_create([
        MVtuberTags(id=1, office_id=1, tag='gen-0', tag_name='ホロライブ0期生'),
        MVtuberTags(id=2, office_id=1, tag='1stgen', tag_name='ホロライブ1期生'),
        MVtuberTags(id=3, office_id=1, tag='gen-2', tag_name='ホロライブ2期生'),
        MVtuberTags(id=4, office_id=1, tag='gamers', tag_name='ホロライブゲーマーズ'),
        MVtuberTags(id=5, office_id=1, tag='gen-3', tag_name='ホロライブ3期生'),
        MVtuberTags(id=6, office_id=1, tag='gen-4', tag_name='ホロライブ4期生'),
        MVtuberTags(id=7, office_id=1, tag='gen-5', tag_name='ホロライブ5期生'),
        MVtuberTags(id=8, office_id=1, tag='holox', tag_name='秘密結社holoX'),
        MVtuberTags(id=9, office_id=1, tag='regloss', tag_name='ReGLOSS'),
        MVtuberTags(id=10, office_id=1, tag='tag_office-staff', tag_name='事務所スタッフ'),
    ])

    # VTuber情報
    MVtubers.objects.bulk_create([
        MVtubers(
            id=1,
            office_id=1,
            name_ja='ときのそら',
            name_en='Tokino Sora',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h1.png',
            thumbnail_filename='h1_t.png',
            catch_text='「そらとものみんなー！元気ー？ときのそらです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/0_そら.mp4',
            youtube_url='https://www.youtube.com/channel/UCp6993wxpyDPHUpavwDFqgg?sub_confirmation=1',
            twitter_url='https://twitter.com/tokino_sora',
            recommended_video1='https://www.youtube.com/watch?v=NT6Pf28eCgQ',
            recommended_video2='https://www.youtube.com/watch?v=ZXF1SzAtFj8',
            recommended_video3='https://www.youtube.com/watch?v=LPEE4MMDieo'
        ),
        MVtubers(
            id=2,
            office_id=1,
            name_ja='ロボ子さん',
            name_en='Robocosan',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h2.png',
            thumbnail_filename='h2_t.png',
            catch_text='「はろーぼー！ロボ子だよー」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2023/06/little-bit.mp4',
            youtube_url='https://www.youtube.com/channel/UCDqI2jOz0weumE8s7paEk6g?sub_confirmation=1',
            twitter_url='https://twitter.com/robocosan',
            recommended_video1='https://www.youtube.com/watch?v=K8n-pGOrpzc',
            recommended_video2='https://www.youtube.com/watch?v=inHAAbWA3Jk',
            recommended_video3='https://www.youtube.com/watch?v=_WuSd5M7va4'
        ),
        MVtubers(
            id=3,
            office_id=1,
            name_ja='AZKi',
            name_en=None,
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h3.png',
            thumbnail_filename='h3_t.png',
            catch_text='「Virtual Diva AZKi 仮想世界の歌姫！音楽と歌うことが大好き！」',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UC0TXe_LYZ4scaW2XMyi5_kw?sub_confirmation=1',
            twitter_url='https://twitter.com/AZKi_VDiVA',
            recommended_video1='https://www.youtube.com/watch?v=IsTij69xLBc',
            recommended_video2='https://www.youtube.com/watch?v=z7EC1VM9L-U',
            recommended_video3='https://www.youtube.com/watch?v=JaTS4xhV7b8'
        ),
        MVtubers(
            id=4,
            office_id=1,
            name_ja='さくらみこ',
            name_en='Sakura Miko',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h4.png',
            thumbnail_filename='h4_t.png',
            catch_text='「にゃっはろ～！ホロライブ所属のエリート巫女アイドルさくらみこですっ！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/04/gif%E5%8B%95%E7%94%BB.gif',
            youtube_url='https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA?sub_confirmation=1',
            twitter_url='https://twitter.com/sakuramiko35',
            recommended_video1='https://www.youtube.com/watch?v=X9zw0QF12Kc',
            recommended_video2='https://www.youtube.com/watch?v=HiLnCY9qjSo',
            recommended_video3='https://www.youtube.com/watch?v=P3kv98KtlFg'
        ),
        MVtubers(
            id=5,
            office_id=1,
            name_ja='星街すいせい',
            name_en='Hoshimachi Suisei',
            tag1=MVtuberTags.objects.get(id=1),
            tag2=None,
            image_filename='h5.png',
            thumbnail_filename='h5_t.png',
            catch_text='「彗星の如く現れたスターの原石！アイドルVTuberの星街すいせいです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/0_すいせい.mp4',
            youtube_url='https://www.youtube.com/channel/UC5CwaMl1eIgY8h02uZw7u8A?sub_confirmation=1',
            twitter_url='https://twitter.com/suisei_hosimati',
            recommended_video1='https://www.youtube.com/watch?v=zLak0dxBKpM',
            recommended_video2='https://www.youtube.com/watch?v=vQHVGXdcqEQ',
            recommended_video3='https://www.youtube.com/watch?v=ZfDYRy17CBY'
        ),
        MVtubers(
            id=6,
            office_id=1,
            name_ja='アキ・ローゼンタール',
            name_en='Aki Rosenthal',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=None,
            image_filename='h6.png',
            thumbnail_filename='h6_t.png',
            catch_text='「アローナ！癒し系ハーフエルフお姉さん、アキロゼと一緒に乾杯しよ？」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/04/GIF本完成.gif',
            youtube_url='https://www.youtube.com/channel/UCFTLzh12_nrtzqBPsTCqenA?sub_confirmation=1',
            twitter_url='https://twitter.com/akirosenthal',
            recommended_video1='https://www.youtube.com/watch?v=Ii7rtNaGlls',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=7,
            office_id=1,
            name_ja='赤井はあと',
            name_en='Akai Haato',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=None,
            image_filename='h7.png',
            thumbnail_filename='h7_t.png',
            catch_text='「こんるーじゅ！赤井はあとよ！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/1_はあと.mp4',
            youtube_url='https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg?sub_confirmation=1',
            twitter_url='https://twitter.com/akaihaato',
            recommended_video1='https://www.youtube.com/watch?v=zXzsdzFR4BA',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=8,
            office_id=1,
            name_ja='白上フブキ',
            name_en='Shirakami Fubuki',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=MVtuberTags.objects.get(id=4),
            image_filename='h8.png',
            thumbnail_filename='h8_t.png',
            catch_text='「こんこんきーつね！白上フブキです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/1_フブキ.mp4',
            youtube_url='https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg?sub_confirmation=1',
            twitter_url='https://twitter.com/shirakamifubuki',
            recommended_video1='https://www.youtube.com/watch?v=eO1jo_onIEg',
            recommended_video2='https://www.youtube.com/watch?v=qvIZWqp-TMY',
            recommended_video3=None
        ),
        MVtubers(
            id=9,
            office_id=1,
            name_ja='夏色まつり',
            name_en='Natsuiro Matsuri',
            tag1=MVtuberTags.objects.get(id=2),
            tag2=None,
            image_filename='h9.png',
            thumbnail_filename='h9_t.png',
            catch_text='「わっしょ～い！ホロライブの清楚担当みんなのアイドル夏色まつりです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/1_まつり.mp4',
            youtube_url='https://youtube.com/channel/UCQ0UDLQCjY0rmuxCDE38FGg?sub_confirmation=1',
            twitter_url='https://twitter.com/natsuiromatsuri',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=10,
            office_id=1,
            name_ja='湊あくあ',
            name_en='Minato Aqua',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h10.png',
            thumbnail_filename='h10_t.png',
            catch_text='「皆さんどうもこんあくあ～！バーチャルアイドル ゲーマー猫耳メイドの湊あくあで～す！！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/2_あくあ.mp4',
            youtube_url='https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg?sub_confirmation=1',
            twitter_url='https://twitter.com/minatoaqua',
            recommended_video1='https://www.youtube.com/watch?v=6bnaBnd4kyU',
            recommended_video2='https://www.youtube.com/watch?v=O8v5S1nhKzo',
            recommended_video3='https://www.youtube.com/watch?v=aGlY6Ueaco0'
        ),
        MVtubers(
            id=11,
            office_id=1,
            name_ja='紫咲シオン',
            name_en='Murasaki Shion',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h11.png',
            thumbnail_filename='h11_t.png',
            catch_text='「こんしお～、紫咲シオンだよ」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/10/829524_727810.gif',
            youtube_url='https://www.youtube.com/channel/UCXTpFs_3PqI41qX2d9tL2Rw?sub_confirmation=1',
            twitter_url='https://twitter.com/murasakishionch',
            recommended_video1='https://www.youtube.com/watch?v=OZmYNcs7-wo',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=12,
            office_id=1,
            name_ja='百鬼あやめ',
            name_en='Nakiri Ayame',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h12.png',
            thumbnail_filename='h12_t.png',
            catch_text='「人間様たちこんなきりー！やほ～～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/2_あやめ.mp4',
            youtube_url='https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg?sub_confirmation=1',
            twitter_url='https://twitter.com/nakiriayame',
            recommended_video1='https://www.youtube.com/watch?v=ClrzryIkpTA',
            recommended_video2='https://www.youtube.com/watch?v=jHd7SPreuAQ',
            recommended_video3='https://www.youtube.com/watch?v=c9VYairGvn4?t=1078'
        ),
        MVtubers(
            id=13,
            office_id=1,
            name_ja='癒月ちょこ',
            name_en='Yuzuki Choco',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h13.png',
            thumbnail_filename='h13_t.png',
            catch_text='「Good evening!my cute students.ちょっこーん！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/10/366159_806304.gif',
            youtube_url='https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg?sub_confirmation=1',
            twitter_url='https://twitter.com/yuzukichococh',
            recommended_video1='https://www.youtube.com/watch?v=n9DqvVNBdVI',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=14,
            office_id=1,
            name_ja='大空スバル',
            name_en='Oozora Subaru',
            tag1=MVtuberTags.objects.get(id=3),
            tag2=None,
            image_filename='h14.png',
            thumbnail_filename='h14_t.png',
            catch_text='「ちわーす！ホロライブ2期生大空スバルっス！！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/04/GIF.gif',
            youtube_url='https://www.youtube.com/channel/UCvzGlP9oQwU--Y0r9id_jnA?sub_confirmation=1',
            twitter_url='https://twitter.com/oozorasubaru',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=15,
            office_id=1,
            name_ja='大神ミオ',
            name_en='Ookami Mio',
            tag1=MVtuberTags.objects.get(id=4),
            tag2=None,
            image_filename='h15.png',
            thumbnail_filename='h15_t.png',
            catch_text='「こんばんみぉーん！大神ミオだよ～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/g_ミオ.mp4',
            youtube_url='https://www.youtube.com/channel/UCp-5t9SrOQwXMU7iIjQfARg?sub_confirmation=1',
            twitter_url='https://twitter.com/ookamimio',
            recommended_video1='https://www.youtube.com/watch?v=XoaUBfmG8Ow',
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=16,
            office_id=1,
            name_ja='猫又おかゆ',
            name_en='Nekomata Okayu',
            tag1=MVtuberTags.objects.get(id=4),
            tag2=None,
            image_filename='h16.png',
            thumbnail_filename='h16_t.png',
            catch_text='「もぐもぐ～おかゆ～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2024/04/Nekomata-Okayu_movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCvaTdHTWBGv3MKj3KVqJVCw?sub_confirmation=1',
            twitter_url='https://twitter.com/nekomataokayu',
            recommended_video1='https://www.youtube.com/watch?v=P9auWa9ON1o',
            recommended_video2='https://www.youtube.com/watch?v=G_L6m4Ww1DI',
            recommended_video3='https://www.youtube.com/watch?v=IHkPvsE5gUI'
        ),
        MVtubers(
            id=17,
            office_id=1,
            name_ja='戌神ころね',
            name_en='Inugami Korone',
            tag1=MVtuberTags.objects.get(id=4),
            tag2=None,
            image_filename='h17.png',
            thumbnail_filename='h17_t.png',
            catch_text='「ぉぁよ～！ゆびゆび～」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/10/368714_768061.gif',
            youtube_url='https://www.youtube.com/channel/UChAnqc_AY5_I3Px5dig3X1Q?sub_confirmation=1',
            twitter_url='https://twitter.com/inugamikorone',
            recommended_video1='https://www.youtube.com/watch?v=I9m2C_Vx1j4',
            recommended_video2='https://www.youtube.com/watch?v=5wCvCFEUzmc',
            recommended_video3=None
        ),
        MVtubers(
            id=18,
            office_id=1,
            name_ja='兎田ぺこら',
            name_en='Usada Pekora',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h18.png',
            thumbnail_filename='h18_t.png',
            catch_text='「こんぺこ！こんぺこ！こんぺこー！兎田ぺこらぺこ～！どうも〜どうも〜」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/3_ぺこら.mp4',
            youtube_url='https://www.youtube.com/channel/UC1DCedRgGHBdm81E1llLhOQ?sub_confirmation=1',
            twitter_url='https://twitter.com/usadapekora',
            recommended_video1='https://www.youtube.com/watch?v=7k-r7P9TXdQ',
            recommended_video2='https://www.youtube.com/watch?v=yy8asHUr9vQ',
            recommended_video3='https://www.youtube.com/watch?v=AAr2lHZLNyU'
        ),
        MVtubers(
            id=19,
            office_id=1,
            name_ja='不知火フレア',
            name_en='Shiranui Flare',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h19.png',
            thumbnail_filename='h19_t.png',
            catch_text='「こんぬいー！ホロライブ3期生の不知火フレアだよ！」',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UCvInZx9h3jC2JzsIzoOebWg?sub_confirmation=1',
            twitter_url='https://twitter.com/shiranuiflare',
            recommended_video1='https://www.youtube.com/watch?v=3y8oIuEkqQs',
            recommended_video2='https://www.youtube.com/watch?v=ogiRp9DaSP8',
            recommended_video3='https://www.youtube.com/watch?v=ZMlPAsIJslA&t=2743s'
        ),
        MVtubers(
            id=20,
            office_id=1,
            name_ja='白銀ノエル',
            name_en='Shirogane Noel',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h20.png',
            thumbnail_filename='h20_t.png',
            catch_text='「こんまっする～！鉄の胃袋大魔神！ 白銀聖騎士団の団長、白銀ノエルです！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/07/MOVIE.mp4',
            youtube_url='https://www.youtube.com/channel/UCdyqAaZDKHXg4Ahi7VENThQ?sub_confirmation=1',
            twitter_url='https://twitter.com/shiroganenoel',
            recommended_video1='https://www.youtube.com/watch?v=Pt4GlDfYwa0',
            recommended_video2='https://www.youtube.com/watch?v=_gb44X05LsU',
            recommended_video3=None
        ),
        MVtubers(
            id=21,
            office_id=1,
            name_ja='宝鐘マリン',
            name_en='Houshou Marine',
            tag1=MVtuberTags.objects.get(id=5),
            tag2=None,
            image_filename='h21.png',
            thumbnail_filename='h21_t.png',
            catch_text='「Ahoy!宝鐘海賊団船長！宝鐘マリンです～！」「ヨーソロー」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2023/03/Houshou-Marine_megane_movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCCzUftO8KOVkV4wQG1vkUvg?sub_confirmation=1',
            twitter_url='https://twitter.com/houshoumarine',
            recommended_video1='https://www.youtube.com/watch?v=3LaDuoHDC_g',
            recommended_video2='https://www.youtube.com/watch?v=WSDkNw2c4A8',
            recommended_video3='https://www.youtube.com/watch?v=Ry0lMtQQEHI'
        ),
        MVtubers(
            id=22,
            office_id=1,
            name_ja='天音かなた',
            name_en='Amane Kanata',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h22.png',
            thumbnail_filename='h22_t.png',
            catch_text='「へい！みんなこんかなた～！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2023/04/Amane-Kanata_pr-movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCZlDXzGoo7d44bwdNObFacg?sub_confirmation=1',
            twitter_url='https://twitter.com/amanekanatach',
            recommended_video1='https://www.youtube.com/watch?v=szUbg1Yar5c',
            recommended_video2='https://www.youtube.com/watch?v=c5czz3xhwTw',
            recommended_video3='https://www.youtube.com/watch?v=FOjfhbv-t6k'
        ),
        MVtubers(
            id=23,
            office_id=1,
            name_ja='角巻わため',
            name_en='Tsunomaki Watame',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h23.png',
            thumbnail_filename='h23_t.png',
            catch_text='「こんばんドドド～！」「わためは悪くないよねぇ？」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/03/210328_角巻わため_GIF.gif',
            youtube_url='https://www.youtube.com/channel/UCqm3BQLlJfvkTsX_hvm0UmA?sub=confirmation=1',
            twitter_url='https://twitter.com/tsunomakiwatame',
            recommended_video1='https://www.youtube.com/watch?v=DGun2cWbPEM',
            recommended_video2='https://www.youtube.com/watch?v=j5n1zqsvfXo',
            recommended_video3='https://www.youtube.com/watch?v=TgiT1DQe_io&t=1977s'
        ),
        MVtubers(
            id=24,
            office_id=1,
            name_ja='常闇トワ',
            name_en='Tokoyami Towa',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h24.png',
            thumbnail_filename='h24_t.png',
            catch_text='「こんやっぴーホロライブ4期生常闇トワ様です」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/03/4_トワ_2.mp4',
            youtube_url='https://www.youtube.com/channel/UC1uv2Oq6kNxgATlCiez59hw?sub_confirmation=1',
            twitter_url='https://twitter.com/tokoyamitowa',
            recommended_video1='https://www.youtube.com/watch?v=Ud73fm4Uoq0',
            recommended_video2='https://www.youtube.com/watch?v=Zc05le75CfI',
            recommended_video3='https://www.youtube.com/watch?v=pSg-0zUrbMQ'
        ),
        MVtubers(
            id=25,
            office_id=1,
            name_ja='姫森ルーナ',
            name_en='Himemori Luna',
            tag1=MVtuberTags.objects.get(id=6),
            tag2=None,
            image_filename='h25.png',
            thumbnail_filename='h25_t.png',
            catch_text='「みんな～、おりゅ～？」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/09/4_ルーナ-1.mp4-1.mp4',
            youtube_url='https://www.youtube.com/channel/UCa9Y57gfeY0Zro_noHRVrnw?sub_confirmation=1',
            twitter_url='https://twitter.com/himemoriluna',
            recommended_video1='https://www.youtube.com/watch?v=DkGOA3Xhr9s',
            recommended_video2='https://www.youtube.com/watch?v=vlqVuLuZl00',
            recommended_video3='https://www.youtube.com/watch?v=Tf9BTiIHGVw'
        ),
        MVtubers(
            id=26,
            office_id=1,
            name_ja='雪花ラミィ',
            name_en='Yukihana Lamy',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h26.png',
            thumbnail_filename='h26_t.png',
            catch_text='「おはらみです、こんらみです」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/08/lamy_profile_movie.mp4',
            youtube_url='https://www.youtube.com/channel/UCFKOVgVbGmX65RxO3EtH3iw?sub_confirmation=1',
            twitter_url='https://twitter.com/yukihanalamy',
            recommended_video1='https://www.youtube.com/watch?v=wIOrGqv3-RU'
        ),
        MVtubers(
            id=27,
            office_id=1,
            name_ja='桃鈴ねね',
            name_en='Momosuzu Nene',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h27.png',
            thumbnail_filename='h27_t.png',
            catch_text='「こんねね～！ホロライブ5期生オレンジ担当、 アイドルVTuberの桃鈴ねねで～す！」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/5_ねね.mp4',
            youtube_url='https://www.youtube.com/channel/UCAWSyEs_Io8MtpY3m-zqILA?sub_confirmation=1',
            twitter_url='https://twitter.com/momosuzunene',
            recommended_video1='https://www.youtube.com/watch?v=YeUkeAq1Dqg?t=290',
            recommended_video2='https://www.youtube.com/watch?v=U0QN3JCHWbw?t=141',
            recommended_video3='https://www.youtube.com/watch?v=K35AflEvvc8'
        ),
        MVtubers(
            id=28,
            office_id=1,
            name_ja='獅白ぼたん',
            name_en='Shishiro Botan',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h28.png',
            thumbnail_filename='h28_t.png',
            catch_text='「ららーいおん♪」「ほならな～」',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/5_ぼたん.mp4',
            youtube_url='https://www.youtube.com/channel/UCUKD-uaobj9jiqB-VXt71mA?sub_confirmation=1',
            twitter_url='https://twitter.com/shishirobotan',
            recommended_video1='https://www.youtube.com/watch?v=Lm1k8TI790Y',
            recommended_video2='https://www.youtube.com/watch?v=7zjvFxCetc0?t=86',
            recommended_video3='https://www.youtube.com/watch?v=TNlSd-snAlo?t=104'
        ),
        MVtubers(
            id=29,
            office_id=1,
            name_ja='尾丸ポルカ',
            name_en='Omaru Polka',
            tag1=MVtuberTags.objects.get(id=7),
            tag2=None,
            image_filename='h29.png',
            thumbnail_filename='h29_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2021/05/5_ぽるか.mp4',
            youtube_url='https://www.youtube.com/channel/UCK9V2B22uJYu3N7eR_BT9QA?sub_confirmation=1',
            twitter_url='https://twitter.com/omarupolka',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=30,
            office_id=1,
            name_ja='ラプラス・ダークネス',
            name_en='La+ Darknesss',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h30.png',
            thumbnail_filename='h30_t.png',
            catch_text='貴様ら、刮目せよ！！',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UCENwRMx5Yh42zWpzURebzTw',
            twitter_url='https://twitter.com/LaplusDarknesss',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=31,
            office_id=1,
            name_ja='鷹嶺ルイ',
            name_en='Takane Lui',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h31.png',
            thumbnail_filename='h31_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_lui.mp4',
            youtube_url='https://www.youtube.com/channel/UCs9_O1tRPMQTHQ-N_L6FU2g',
            twitter_url='https://twitter.com/takanelui',
            recommended_video1='https://www.youtube.com/watch?v=jYWhdr73i6A',
            recommended_video2='https://www.youtube.com/watch?v=O0aSJdN3mVY',
            recommended_video3='https://www.youtube.com/watch?v=5t60NWXXkQI'
        ),
        MVtubers(
            id=32,
            office_id=1,
            name_ja='博衣こより',
            name_en='Hakui Koyori',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h32.png',
            thumbnail_filename='h32_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_koyori.mp4',
            youtube_url='https://www.youtube.com/channel/UC6eWCld0KwmyHFbAqK3V-Rw',
            twitter_url='https://twitter.com/hakuikoyori',
            recommended_video1='https://www.youtube.com/watch?v=7ctmEk_35Yc',
            recommended_video2='https://www.youtube.com/watch?v=Mt5SB2igQUM',
            recommended_video3='https://www.youtube.com/watch?v=PIK13uH30gg'
        ),
        MVtubers(
            id=33,
            office_id=1,
            name_ja='沙花叉クロヱ',
            name_en='Sakamata Chloe',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h33.png',
            thumbnail_filename='h33_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_kuroe.mp4',
            youtube_url='https://www.youtube.com/channel/UCIBY1ollUsauvVi4hW4cumw',
            twitter_url='https://twitter.com/sakamatachloe',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=34,
            office_id=1,
            name_ja='風真いろは',
            name_en='Kazama Iroha',
            tag1=MVtuberTags.objects.get(id=8),
            tag2=None,
            image_filename='h34.png',
            thumbnail_filename='h34_t.png',
            catch_text=None,
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2020/07/movie_iroha.mp4',
            youtube_url='https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ',
            twitter_url='https://twitter.com/kazamairohach',
            recommended_video1='https://www.youtube.com/watch?v=ZQveWRj0u5E',
            recommended_video2='https://www.youtube.com/watch?v=au57Syx7wuQ',
            recommended_video3='https://www.youtube.com/watch?v=PIK13uH30gg'
        ),
        MVtubers(
            id=35,
            office_id=1,
            name_ja='火威青',
            name_en='Hiodoshi Ao',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h35.png',
            thumbnail_filename='h35_t.png',
            catch_text='趣味は絵を描くこと。それから仕事は、絵を描くことかな。',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/channel/UCMGfV7TVTmHhEErVJg1oHBQ',
            twitter_url='https://twitter.com/hiodoshiao',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=36,
            office_id=1,
            name_ja='音乃瀬奏',
            name_en='Otonose Kanade',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h36.png',
            thumbnail_filename='h36_t.png',
            catch_text='ここが私のステージだから！',
            introduction_video_url=None,
            youtube_url='https://youtube.com/@OtonoseKanade',
            twitter_url='https://twitter.com/otonosekanade',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=37,
            office_id=1,
            name_ja='一条莉々華',
            name_en='Ichijou Ririka',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h37.png',
            thumbnail_filename='h37_t.png',
            catch_text='この一条莉々華に任せておきなさい！',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/@IchijouRirika',
            twitter_url='https://twitter.com/ichijouririka',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=38,
            office_id=1,
            name_ja='儒烏風亭らでん',
            name_en='Juufuutei Raden',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h38.png',
            thumbnail_filename='h38_t.png',
            catch_text='ちょいと一席付き合ってみませんか？',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/@JuufuuteiRaden',
            twitter_url='https://twitter.com/juufuuteiraden',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=39,
            office_id=1,
            name_ja='轟はじめ',
            name_en='Todoroki Hajime',
            tag1=MVtuberTags.objects.get(id=9),
            tag2=None,
            image_filename='h39.png',
            thumbnail_filename='h39_t.png',
            catch_text='押忍！なんか、番長っぽくなってきたかも！',
            introduction_video_url=None,
            youtube_url='https://www.youtube.com/@TodorokiHajime',
            twitter_url='https://twitter.com/todoroki_hajime',
            recommended_video1=None,
            recommended_video2=None,
            recommended_video3=None
        ),
        MVtubers(
            id=40,
            office_id=1,
            name_ja='友人A（えーちゃん）',
            name_en='Friend-A',
            tag1=MVtuberTags.objects.get(id=10),
            tag2=None,
            image_filename='h40.png',
            thumbnail_filename='h40_t.png',
            catch_text='こんにちは、ホロライブスタッフの友人Aです。',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/05/website_achan.mp4',
            youtube_url='https://www.youtube.com/channel/UCJFZiqLMntJufDCHc6bQixg',
            twitter_url='https://twitter.com/achan_UGA',
            recommended_video1='https://www.youtube.com/watch?v=ApKuitWq-TE',
            recommended_video2='https://www.youtube.com/watch?v=fUQALk8Ub2I',
            recommended_video3='https://www.youtube.com/watch?v=fUQALk8Ub2I'
        ),
        MVtubers(
            id=41,
            office_id=1,
            name_ja='春先のどか',
            name_en='Harusaki Nodoka',
            tag1=MVtuberTags.objects.get(id=10),
            tag2=None,
            image_filename='h41.png',
            thumbnail_filename='h41_t.png',
            catch_text='おはようございます！ホロライブ新人スタッフの春先のどかです✨',
            introduction_video_url='https://hololive.hololivepro.com/wp-content/uploads/2022/05/website_nodoka.mp4',
            youtube_url='https://www.youtube.com/channel/UCJFZiqLMntJufDCHc6bQixg',
            twitter_url='https://twitter.com/harusakinodoka',
            recommended_video1='https://www.youtube.com/watch?v=ApKuitWq-TE',
            recommended_video2='https://www.youtube.com/watch?v=V1OzY9Z8vqY',
            recommended_video3=None
        ),
    ])

    # VTuberプロフィール情報
    MVtubersProfiles.objects.bulk_create([
        MVtubersProfiles(id=1, vtuber_id=1, title='誕生日', content='5月15日'),
        MVtubersProfiles(id=2, vtuber_id=1, title='初配信日', content='9月7日'),
        MVtubersProfiles(id=3, vtuber_id=1, title='身長', content='160㎝'),
        MVtubersProfiles(id=4, vtuber_id=1, title='ユニット', content='ホロライブ0期生'),
        MVtubersProfiles(id=5, vtuber_id=1, title='イラストレーター', content='<a href="https://twitter.com/ordan" target="_blank">おるだん</a>'),
        MVtubersProfiles(id=6, vtuber_id=1, title='夢', content='横浜アリーナで単独ライブがしたい！'),
        MVtubersProfiles(id=7, vtuber_id=1, title='ファンネーム', content='そらとも'),
        MVtubersProfiles(id=8, vtuber_id=1, title='ハッシュタグ', content='配信タグ：#ときのそら生放送<br/>#ときのそら実況するってよ<br/>ファンアート：#そらArt'),
        MVtubersProfiles(id=9, vtuber_id=1, title='Words', content='そらとも:ファンネーム<br/>ぬんぬん:頷きの音が定着したもの。<br/>(๑╹ᆺ╹)この顔でぬんぬんとコメントするのが配信待機の定番になっている。'),
        MVtubersProfiles(id=10, vtuber_id=1, title='得意な配信/よくやる配信', content='歌枠、のんびりゲーム'),
        MVtubersProfiles(id=11, vtuber_id=1, title='趣味', content='カラオケ、御朱印お参り巡り、リズムゲーム'),
        MVtubersProfiles(id=12, vtuber_id=1, title='好きなもの', content='スイーツ、中華料理、猫、ボーカロイド'),
        MVtubersProfiles(id=13, vtuber_id=1, title='特技', content='ホラーゲームを怖がらずに攻略すること'),
        MVtubersProfiles(id=14, vtuber_id=2, title='誕生日', content='5月23日'),
        MVtubersProfiles(id=15, vtuber_id=2, title='デビュー日', content='3月9日'),
        MVtubersProfiles(id=16, vtuber_id=2, title='身長', content='154㎝'),
        MVtubersProfiles(id=17, vtuber_id=2, title='ユニット', content='ホロライブ0期生'),
        MVtubersProfiles(id=18, vtuber_id=2, title='3Dモデラー', content='<a href="https://twitter.com/kuromaru9" target="_blank">kuromaru9</a>'),
        MVtubersProfiles(id=19, vtuber_id=2, title='ファンネーム', content='ろぼさー'),
        MVtubersProfiles(id=20, vtuber_id=2, title='ハッシュタグ', content='配信タグ：#ロボ子生放送<br/>ファンアート：#ロボ子Art'),
        MVtubersProfiles(id=21, vtuber_id=3, title='誕生日', content='7月1日'),
        MVtubersProfiles(id=22, vtuber_id=3, title='身長', content='158cm'),
        MVtubersProfiles(id=23, vtuber_id=3, title='ユニット', content='ホロライブ0期生<br/>SorAZ<br/>Shotgun Rose'),
        MVtubersProfiles(id=24, vtuber_id=3, title='3Dモデラー', content='<a href="https://twitter.com/ksk_st" target="_blank">加速サトウ</a>'),
        MVtubersProfiles(id=25, vtuber_id=3, title='夢', content='誰かの記憶に残る音楽を作ること'),
        MVtubersProfiles(id=26, vtuber_id=3, title='ファンネーム', content='開拓者'),
        MVtubersProfiles(id=27, vtuber_id=3, title='ハッシュタグ', content='ファンアート：#AZKiART<br/>配信タグ：#あずきんち<br/>ホロリー＆聖地巡礼：#どこAZ<br/>楽曲感想：#AZ歌<br/>ボイス感想：#AZ声<br/>ショート：#ぷちあず'),
        MVtubersProfiles(id=28, vtuber_id=3, title='Words', content='床：感情になったときに使う言葉<br/>天井：感情になったときに使う言葉'),
        MVtubersProfiles(id=29, vtuber_id=3, title='Message', content='こんあずきー！AZKiです！主に歌を中心とした配信を行っています ！<br/>開拓者のみんなの心に寄り添える歌や音楽をつくれるようにこれからも頑張ります！'),
        MVtubersProfiles(id=30, vtuber_id=3, title='得意な配信/よくやる配信', content='メイン：歌枠<br/>たまに：ゲーム'),
        MVtubersProfiles(id=31, vtuber_id=3, title='趣味/特技/好きな動物', content='曲作り/料理/シマエナガ'),
        MVtubersProfiles(id=32, vtuber_id=4, title='誕生日', content='3月5日'),
        MVtubersProfiles(id=33, vtuber_id=4, title='デビュー日', content='8月1日'),
        MVtubersProfiles(id=34, vtuber_id=4, title='身長', content='152㎝'),
        MVtubersProfiles(id=35, vtuber_id=4, title='ユニット', content='ホロライブ0期生'),
        MVtubersProfiles(id=36, vtuber_id=4, title='イラストレーター', content='<a href="https://twitter.com/taikonotuki13" target="_blank">田中雄一</a>'),
        MVtubersProfiles(id=37, vtuber_id=4, title='新衣装デザイン', content='<a href="https://twitter.com/ordan" target="_blank">おるだん</a>'),
        MVtubersProfiles(id=38, vtuber_id=4, title='夢', content='誰からもエリートと思われるような唯一無二のトップエリート巫女アイドルになること！そしてずっとみんなを笑顔に出来るような人であり続ける事！'),
        MVtubersProfiles(id=39, vtuber_id=4, title='ファンネーム', content='35Ｐ'),
        MVtubersProfiles(id=40, vtuber_id=4, title='ハッシュタグ', content='配信タグ：#みこなま<br/>ファンアート：#miko_Art<br/>MMD作品：#さくらみこMMD'),
        MVtubersProfiles(id=41, vtuber_id=4, title='Words', content='「にゃっはろ～！」：さくらみこ特有の挨拶<br/>「おつみこ～！」：さくらみこ特有の締めの挨拶<br/>「○○にぇ」：「ねぇ」の活用<br/>「てんたい」：天才<br/>「ぴこーん！」：閃いた音<br/>「みこ畜」：朝方まで配信をすること<br/>「エリート」：努力して頑張り続ける人のこと<br/>「しけてんにぇ～」：しけている様　結果が芳しくない<br/>「みこしってゆよ～」：実は知らない　or 巫女の力で予知している様<br/>「あっちゅ！あっちゅ！」：熱い（マグマでダメージを受けている時に使われる）'),
        MVtubersProfiles(id=42, vtuber_id=4, title='Message', content='１人からはじまった活動がいつのまにかたくさんの仲間とそして大好きなファン（３５P）のみんなと毎日楽しく活動できてます！みんなにたくさん支えられている分、みこもみんなを毎日笑顔にさせれるようにエリートにみこらしく！配信やアイドル 活動をがんばっていくのでいつでも会いに来てにぇ！'),
        MVtubersProfiles(id=43, vtuber_id=4, title='得意な配信/よくやる配信', content='ゲーム実況、映画同時視聴、企画、たまに歌'),
        MVtubersProfiles(id=44, vtuber_id=4, title='特技', content='サムネ作り、全ロス（by 35P)、家庭料理'),
        MVtubersProfiles(id=45, vtuber_id=5, title='誕生日', content='3月22日'),
        MVtubersProfiles(id=46, vtuber_id=5, title='デビュー日', content='3月22日'),
        MVtubersProfiles(id=47, vtuber_id=5, title='身長', content='160㎝'),
        MVtubersProfiles(id=48, vtuber_id=5, title='ユニット', content='ホロライブ0期生'),
        MVtubersProfiles(id=49, vtuber_id=5, title='メイク担当', content='<a href="https://twitter.com/_17meisai23" target="_blank">手島nari</a>'),
        MVtubersProfiles(id=50, vtuber_id=5, title='ファンネーム', content='星詠み'),
        MVtubersProfiles(id=51, vtuber_id=5, title='ハッシュタグ', content='配信タグ：#ほしまちすたじお<br/>ファンアート：#ほしまちぎゃらりー'),
        MVtubersProfiles(id=52, vtuber_id=6, title='誕生日', content='2月17日'),
        MVtubersProfiles(id=53, vtuber_id=6, title='初配信日', content='6月1日'),
        MVtubersProfiles(id=54, vtuber_id=6, title='身長', content='162㎝'),
        MVtubersProfiles(id=55, vtuber_id=6, title='ユニット', content='ホロライブ1期生'),
        MVtubersProfiles(id=56, vtuber_id=6, title='イラストレーター', content='<a href="https://twitter.com/akitake_a" target="_blank">安曇アキタケ</a>'),
        MVtubersProfiles(id=57, vtuber_id=6, title='夢/目標', content='一家に一アキロゼ！！<br/>VRやARを通してみんなにたくさん会いにいけるようになりたい！！<br/>いつかエンターテインメントショーをやってみたいな！！'),
        MVtubersProfiles(id=58, vtuber_id=6, title='ファンネーム', content='ロゼ隊'),
        MVtubersProfiles(id=59, vtuber_id=6, title='ハッシュタグ', content='配信タグ：#アキびゅーわーるど<br/>ファンアート：#アロ絵'),
        MVtubersProfiles(id=60, vtuber_id=6, title='Message', content='みんなの生活に彩りを感じてもらえるような近所のお姉さんみたいな存在になれたら嬉しいかな～！<br/>アキロゼと一緒に色んな景色をみよう！！'),
        MVtubersProfiles(id=61, vtuber_id=6, title='得意な配信/よくやる配信', content='晩酌雑談/歌枠（懐メロ多め）/ゲーム実況<br/>求められる配信は<br/>絶叫のプロによるホラゲ実況<br/>ASMR飯テロ配信'),
        MVtubersProfiles(id=62, vtuber_id=6, title='趣味/特技', content='お酒と料理と音ゲーが大好き！<br/>アロマテラピーインストラクター有資格<br/>ベリーダンス'),
        MVtubersProfiles(id=63, vtuber_id=7, title='誕生日', content='8月10日'),
        MVtubersProfiles(id=64, vtuber_id=7, title='初配信日', content='6月2日'),
        MVtubersProfiles(id=65, vtuber_id=7, title='身長', content='154cm'),
        MVtubersProfiles(id=66, vtuber_id=7, title='ユニット', content='ホロライブ1期生'),
        MVtubersProfiles(id=67, vtuber_id=7, title='イラストレーター', content='<a href="https://twitter.com/haruyuki_nijyou" target="_blank">はる雪</a>'),
        MVtubersProfiles(id=68, vtuber_id=7, title='ファンネーム', content='はあとん'),
        MVtubersProfiles(id=69, vtuber_id=7, title='ハッシュタグ', content='配信タグ：#はあちゃまなう<br/>ファンアート：#はあとart'),
        MVtubersProfiles(id=70, vtuber_id=8, title='誕生日', content='10月5日'),
        MVtubersProfiles(id=71, vtuber_id=8, title='初配信日', content='6月1日'),
        MVtubersProfiles(id=72, vtuber_id=8, title='身長', content='155cm'),
        MVtubersProfiles(id=73, vtuber_id=8, title='ユニット', content='ホロライブ1期生/ホロライブゲーマーズ'),
        MVtubersProfiles(id=74, vtuber_id=8, title='イラストレーター', content='<a href="https://twitter.com/lemon_mito" target="_blank">凪白みと</a>'),
        MVtubersProfiles(id=75, vtuber_id=8, title='ファンネーム', content='すこん部/Friends'),
        MVtubersProfiles(id=76, vtuber_id=8, title='ハッシュタグ', content='配信タグ：#フブキch<br/>ファンアート：#絵フブキ'),
        MVtubersProfiles(id=77, vtuber_id=8, title='夢', content='みんなで沢山ライブ<br/>ソロアルバム発売<br/>MC経験<br/>すこん部のみんなと楽しいことを沢山する！'),
        MVtubersProfiles(id=78, vtuber_id=8, title='配信中に飲んだり食べたりしているもの', content='お茶が一番好きです！特に緑茶<br/>紅茶とオレンジジュースも好き<br/>食べ物はグミやジャーキー'),
        MVtubersProfiles(id=79, vtuber_id=9, title='誕生日', content='7月22日'),
        MVtubersProfiles(id=80, vtuber_id=9, title='初配信日', content='6月1日'),
        MVtubersProfiles(id=81, vtuber_id=9, title='身長', content='152cm'),
        MVtubersProfiles(id=82, vtuber_id=9, title='ユニット', content='ホロライブ1期生'),
        MVtubersProfiles(id=83, vtuber_id=9, title='イラストレーター', content='<a href="https://twitter.com/halllki" target="_blank">皆村春樹</a>'),
        MVtubersProfiles(id=84, vtuber_id=9, title='夢', content='最強アイドル＆声優'),
        MVtubersProfiles(id=85, vtuber_id=9, title='ファンネーム', content='まつりす'),
        MVtubersProfiles(id=86, vtuber_id=9, title='ハッシュタグ', content='配信タグ：#夏まつch<br/>ファンアート：＃祭絵'),
        MVtubersProfiles(id=87, vtuber_id=9, title='Words', content='Vオタ、清楚、凸待ち0人、声優、まつりす、エビフライオン、ガチャ、ドーナツ'),
        MVtubersProfiles(id=88, vtuber_id=9, title='Message', content='自分の思うアイドルらしさを全力で魅せてやるんだから！<br/>少しのわがままは許してねっ！'),
        MVtubersProfiles(id=89, vtuber_id=9, title='得意な配信/よくやる配信', content='歌やゲームを中心にリスナーさんと楽しめることをやっていきます！'),
        MVtubersProfiles(id=90, vtuber_id=9, title='趣味/特技/好きなもの', content='趣味⇒FPSゲーム、歌うこと<br/>特技⇒柔軟、声変え<br/>好きなもの⇒VTuber、ドーナツ'),
        MVtubersProfiles(id=91, vtuber_id=10, title='誕生日', content='12月1日'),
        MVtubersProfiles(id=92, vtuber_id=10, title='初配信日', content='8月8日'),
        MVtubersProfiles(id=93, vtuber_id=10, title='身長', content='148㎝'),
        MVtubersProfiles(id=94, vtuber_id=10, title='ユニット', content='ホロライブ2期生'),
        MVtubersProfiles(id=95, vtuber_id=10, title='イラストレーター', content='<a href="https://twitter.com/umaiyo_puyoman" target="_blank">がおう</a>'),
        MVtubersProfiles(id=96, vtuber_id=10, title='夢', content='銀河一最強アイドル'),
        MVtubersProfiles(id=97, vtuber_id=10, title='ファンネーム', content='あくあクルー'),
        MVtubersProfiles(id=98, vtuber_id=10, title='ハッシュタグ', content='配信タグ：#湊あくあ生放送<br/>ファンアート：#あくあーと'),
        MVtubersProfiles(id=99, vtuber_id=10, title='Words', content='オニオン、44.5、大天使、AMT、AKUKIN、<br/>( ^)o(^ )、うぱー、思い込みの狂気、ソロライブ、IQ5000、凸０、中笑い、NEKO、あくあ色'),
        MVtubersProfiles(id=100, vtuber_id=10, title='Message', content='みんなをあくあ色に染めちゃうんだから！！ついてきてね！'),
        MVtubersProfiles(id=101, vtuber_id=10, title='よくやる配信', content='オンラインゲーム中心にFPSからアクションゲームまで幅広くプレイしてます！'),
        MVtubersProfiles(id=102, vtuber_id=10, title='趣味', content='歌うこと'),
        MVtubersProfiles(id=103, vtuber_id=10, title='好きなもの', content='アニメ、漫画、オムライス'),
        MVtubersProfiles(id=104, vtuber_id=10, title='特技', content='ゲーム'),
        MVtubersProfiles(id=105, vtuber_id=11, title='誕生日', content='12月8日'),
        MVtubersProfiles(id=106, vtuber_id=11, title='初配信日', content='8月17日'),
        MVtubersProfiles(id=107, vtuber_id=11, title='身長', content='145cm'),
        MVtubersProfiles(id=108, vtuber_id=11, title='ユニット', content='ホロライブ2期生'),
        MVtubersProfiles(id=109, vtuber_id=11, title='イラストレーター', content='<a href="https://twitter.com/Tam_U" target="_blank">Tam-U</a>'),
        MVtubersProfiles(id=110, vtuber_id=11, title='ファンネーム', content='塩っ子'),
        MVtubersProfiles(id=111, vtuber_id=11, title='呼称', content='シオンちゃん、シオン、しおんたん'),
        MVtubersProfiles(id=112, vtuber_id=11, title='ハッシュタグ', content='配信タグ：#紫咲シオン<br/>ファンアート：#シオンの書物'),
        MVtubersProfiles(id=113, vtuber_id=11, title='夢', content='世界のみんなを笑顔にする！！'),
        MVtubersProfiles(id=114, vtuber_id=11, title='Words', content='ね゛え゛ぇぇえええ<br/>ばぁ～か<br/>ブチ切れ発狂パラダイス<br/>ブラジル(トークテーマが脱線すること)<br/>クソガキ<br/>寝坊<br/>ハバ卒<br/>イン◯タ(絶対やらない)'),
        MVtubersProfiles(id=115, vtuber_id=11, title='よくやる配信', content='歌枠、ゲーム、歌ってみたとか！！！なんでもやるよ！！'),
        MVtubersProfiles(id=116, vtuber_id=11, title='好きなこと', content='歌うこと、ゲーム、アニメ鑑賞、食べること、寝る！！！！'),
        MVtubersProfiles(id=117, vtuber_id=11, title='メッセージ', content='みんないつもありがとう！！！！！すしだよ！！'),
        MVtubersProfiles(id=118, vtuber_id=12, title='誕生日', content='12月13日'),
        MVtubersProfiles(id=119, vtuber_id=12, title='初配信日', content='9月3日'),
        MVtubersProfiles(id=120, vtuber_id=12, title='身長', content='152㎝'),
        MVtubersProfiles(id=121, vtuber_id=12, title='ユニット', content='ホロライブ2期生'),
        MVtubersProfiles(id=122, vtuber_id=12, title='イラストレーター', content='<a href="https://twitter.com/nana_kaguraaa" target="_blank">ななかぐら</a>'),
        MVtubersProfiles(id=123, vtuber_id=12, title='夢', content='オリジナルソロ曲リリース！！<br/>ワンマンライブ！！！'),
        MVtubersProfiles(id=124, vtuber_id=12, title='ファンネーム', content='百鬼組'),
        MVtubersProfiles(id=125, vtuber_id=12, title='ハッシュタグ', content='配信タグ：#百鬼あやめch<br/>ファンアート：#百鬼絵巻'),
        MVtubersProfiles(id=126, vtuber_id=12, title='Words', content='式神：業、不知火　<br/>ぽよ余：フブキちゃんが生み出したマスコットキャラクター<br/>ミーム：かわ余（リスナーの人間様達が可愛いと思った時によく使う言葉）'),
        MVtubersProfiles(id=127, vtuber_id=12, title='Message', content='ここまでプロフィールを見てくれてありがとう！！<br/>余の配信ではリスナーの人間様と余が皆で一緒に笑顔で楽しめる温かい場所を目標に配信を頑張っています！<br/>歌もゲームも一生懸命頑張っているのできになったら見に来てください！'),
        MVtubersProfiles(id=128, vtuber_id=12, title='得意な配信/よくやる配信', content='雑談、歌枠、晩酌'),
        MVtubersProfiles(id=129, vtuber_id=12, title='好きなこと', content='御朱印集め、アニメ鑑賞、ゲーム、神社巡り'),
        MVtubersProfiles(id=130, vtuber_id=13, title='誕生日', content='2月14日'),
        MVtubersProfiles(id=131, vtuber_id=13, title='初配信日', content='9月4日'),
        MVtubersProfiles(id=132, vtuber_id=13, title='身長', content='165cm'),
        MVtubersProfiles(id=133, vtuber_id=13, title='ユニット', content='ホロライブ2期生'),
        MVtubersProfiles(id=134, vtuber_id=13, title='イラストレーター', content='<a href="https://twitter.com/shima_je" target="_blank">桝石きのと</a>'),
        MVtubersProfiles(id=135, vtuber_id=13, title='ファンネーム', content='ちょこめいと'),
        MVtubersProfiles(id=136, vtuber_id=13, title='ハッシュタグ', content='配信タグ：#癒月診療所<br/>ファンアート：#しょこらーと'),
        MVtubersProfiles(id=137, vtuber_id=14, title='誕生日', content='7月2日'),
        MVtubersProfiles(id=138, vtuber_id=14, title='初配信日', content='9月16日'),
        MVtubersProfiles(id=139, vtuber_id=14, title='身長', content='154cm'),
        MVtubersProfiles(id=140, vtuber_id=14, title='ユニット', content='ホロライブ2期生'),
        MVtubersProfiles(id=141, vtuber_id=14, title='イラストレーター', content='<a href="https://twitter.com/ui_shig" target="_blank">しぐれうい</a>'),
        MVtubersProfiles(id=142, vtuber_id=14, title='ファンネーム', content='スバ友'),
        MVtubersProfiles(id=143, vtuber_id=14, title='ハッシュタグ', content='配信タグ：#生スバル<br/>ファンアート：#プロテインザスバル'),
        MVtubersProfiles(id=144, vtuber_id=14, title='趣味など', content='映画鑑賞、おさんぽ'),
        MVtubersProfiles(id=145, vtuber_id=15, title='誕生日', content='8月20日'),
        MVtubersProfiles(id=146, vtuber_id=15, title='初配信日', content='12月7日'),
        MVtubersProfiles(id=147, vtuber_id=15, title='身長', content='160cm'),
        MVtubersProfiles(id=148, vtuber_id=15, title='ユニット', content='ホロライブゲーマーズ'),
        MVtubersProfiles(id=149, vtuber_id=15, title='イラストレーター', content='<a href="https://twitter.com/AC______" target="_blank">泉彩</a>'),
        MVtubersProfiles(id=150, vtuber_id=15, title='ファンネーム', content='ミオファ（みおーんファミリー）'),
        MVtubersProfiles(id=151, vtuber_id=15, title='ハッシュタグ', content='配信タグ：#ミオかわいい<br/>ファンアート：#みおーん絵'),
        MVtubersProfiles(id=152, vtuber_id=16, title='誕生日', content='2月22日'),
        MVtubersProfiles(id=153, vtuber_id=16, title='初配信日', content='4月6日'),
        MVtubersProfiles(id=154, vtuber_id=16, title='身長', content='152cm'),
        MVtubersProfiles(id=155, vtuber_id=16, title='ユニット', content='ホロライブゲーマーズ'),
        MVtubersProfiles(id=156, vtuber_id=16, title='イラストレーター', content='<a href="https://twitter.com/kami_shun0505" target="_blank">神岡ちろる</a>'),
        MVtubersProfiles(id=157, vtuber_id=16, title='夢', content='ゲームが大好きでホロライブにやってきたけど、大好きなみんなと一緒にいることで沢山やりたいことができた！<br/>歌もダンスももちろん！ゲームも！全力で毎日楽しむ！<br/>等身大の自分で毎日応援してくれるみんなとらぶらぶちゅっちゅしたい。<br/>(切実)'),
        MVtubersProfiles(id=158, vtuber_id=16, title='ファンネーム', content='おにぎりゃー'),
        MVtubersProfiles(id=159, vtuber_id=16, title='ハッシュタグ', content='配信タグ：#生おかゆ<br/>ファンアート：#絵かゆ'),
        MVtubersProfiles(id=160, vtuber_id=16, title='Message', content='もぐもぐおかゆ～！猫又おかゆです！<br/>普段はゲーム配信してたり歌を歌ったり楽しく暮らしてるよ！<br/>みんなからは全肯定猫って呼ばれたり、何故か有罪猫って言われたり…なんだかイメージが湧かないね！直接会いに来て～～！ばいば～い！'),
        MVtubersProfiles(id=161, vtuber_id=16, title='趣味', content='・ゲーム(せっかくなので細かい好みを書いていきます)<br/>ローグライク、RPG、シミュレーション、レトロなゲ ーム大好き<p>・MIX<br/>ホロライブに入ってから歌う機会が増えてお勉強しました。ﾑｽﾞｶｼｲ</p><p>・野球<br/>夏は頻繁に某チームを応援してます。<br/>(マスコットキャラクターが可愛くて興味を持った)</p><p>・せく♡ら<br/>“気持ち悪い”その一言で元気になってしまう。</p>'),
        MVtubersProfiles(id=162, vtuber_id=16, title='好きなもの', content='お茶漬け、紅茶、猫ミーム、ホロライブのみんな、おにぎりゃー'),
        MVtubersProfiles(id=163, vtuber_id=16, title='特技', content='70点くらいのモノマネ、ASMR、全肯定(肯定しす ぎてツッコミができない)'),
        MVtubersProfiles(id=164, vtuber_id=17, title='誕生日', content='10月1日'),
        MVtubersProfiles(id=165, vtuber_id=17, title='初配信日', content='4月13日'),
        MVtubersProfiles(id=166, vtuber_id=17, title='身長', content='156cm'),
        MVtubersProfiles(id=167, vtuber_id=17, title='ユニット', content='ホロライブゲーマーズ'),
        MVtubersProfiles(id=168, vtuber_id=17, title='イラストレーター', content='<a href="https://twitter.com/fuka_hire" target="_blank">フカヒレ</a>'),
        MVtubersProfiles(id=169, vtuber_id=17, title='ファンネーム', content='ころねすきー'),
        MVtubersProfiles(id=170, vtuber_id=17, title='ハッシュタグ', content='配信タグ：#生神もんざえもん<br/>ファンアート：#できたてころね'),
        MVtubersProfiles(id=171, vtuber_id=18, title='誕生日', content='1月12日'),
        MVtubersProfiles(id=172, vtuber_id=18, title='初配信日', content='7月17日'),
        MVtubersProfiles(id=173, vtuber_id=18, title='身長', content='153cm'),
        MVtubersProfiles(id=174, vtuber_id=18, title='ユニット', content='ホロライブ３期生'),
        MVtubersProfiles(id=175, vtuber_id=18, title='イラストレーター', content='<a href="https://twitter.com/yuukihagure" target="_blank">憂姫はぐれ</a>'),
        MVtubersProfiles(id=176, vtuber_id=18, title='夢', content='全世界野うさぎ計画！！！！！！！！！！'),
        MVtubersProfiles(id=177, vtuber_id=18, title='ファンネーム', content='野うさぎ同盟'),
        MVtubersProfiles(id=178, vtuber_id=18, title='ハッシュタグ', content='配信タグ：#ぺこらいぶ<br/>ファンアート：#ぺこらーと'),
        MVtubersProfiles(id=179, vtuber_id=18, title='Words', content='ぺこらんど<br/>– ぺこらの生まれた国<br/>◯◯ぺこ<br/>– ぺこらの語尾<br/>どんちゃん<br/>– 首元にいるうさぎ（生きてます）<br/>きtらあああああ<br/>– ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!<br/>開始ポエム<br/>– 配信の最初に綴るポエム'),
        MVtubersProfiles(id=180, vtuber_id=18, title='よくやる配信', content='ゲーム配信をメインに色々配信しているぺこ！'),
        MVtubersProfiles(id=181, vtuber_id=18, title='好きなこと', content='配信、ゲーム、漫画、映画、寝ること！'),
        MVtubersProfiles(id=182, vtuber_id=18, title='呼称', content='ぺこーら、ぺこちゃん、うーペー、長'),
        MVtubersProfiles(id=183, vtuber_id=19, title='誕生日', content='4月2日'),
        MVtubersProfiles(id=184, vtuber_id=19, title='初配信日', content='8月7日'),
        MVtubersProfiles(id=185, vtuber_id=19, title='身長', content='158cm'),
        MVtubersProfiles(id=186, vtuber_id=19, title='ユニット', content='ホロライブ3期生'),
        MVtubersProfiles(id=187, vtuber_id=19, title='イラストレーター', content='<a href="https://twitter.com/lalalalack" target="_blank">lack</a>'),
        MVtubersProfiles(id=188, vtuber_id=19, title='夢', content='私のことをもっと知ってもらいたい、私の歌をもっともっとみんなに聞いてもらいたいな！'),
        MVtubersProfiles(id=189, vtuber_id=19, title='ファンネーム', content='エルフレンド'),
        MVtubersProfiles(id=190, vtuber_id=19, title='ハッシュタグ', content='配信タグ：#フレアストリーム<br/>ファンアート：#しらぬえ'),
        MVtubersProfiles(id=191, vtuber_id=19, title='Message', content='歌うの大好き！ゲームも大好き！でもまだまだゲームは下手っぴだけど楽しむことは誰にも負けない！<br/>     苦手なゲームも死にゲーも楽しくプレイしゃうぞ！もっと私のことを知ってくれたら嬉しいな！'),
        MVtubersProfiles(id=192, vtuber_id=19, title='好きなもの/よくやる配信', content='歌・ゲーム'),
        MVtubersProfiles(id=193, vtuber_id=19, title='趣味', content='歌う、お絵描き、推しを愛でる'),
        MVtubersProfiles(id=194, vtuber_id=19, title='特技', content='裏声なしで三オクターブくらい出る'),
        MVtubersProfiles(id=195, vtuber_id=20, title='誕生日', content='11月24日'),
        MVtubersProfiles(id=196, vtuber_id=20, title='初配信日', content='8月8日'),
        MVtubersProfiles(id=197, vtuber_id=20, title='身長', content='158cm'),
        MVtubersProfiles(id=198, vtuber_id=20, title='ユニット', content='ホロライブ3期生'),
        MVtubersProfiles(id=199, vtuber_id=20, title='イラストレーター', content='<a href="https://twitter.com/wait_ar" target="_blank">わたお</a>'),
        MVtubersProfiles(id=200, vtuber_id=20, title='ファンネーム', content='白銀聖騎士団'),
        MVtubersProfiles(id=201, vtuber_id=20, title='ハッシュタグ', content='配信タグ：#ノエルーム<br/>ファンアート：#ノエラート'),
        MVtubersProfiles(id=202, vtuber_id=20, title='趣味', content='食べること！ ゲームすること！ アニメみること！'),
        MVtubersProfiles(id=203, vtuber_id=20, title='特技', content='まっするメトロノーム、朗読(？)、ASMR'),
        MVtubersProfiles(id=204, vtuber_id=20, title='好きなもの', content='牛丼！　三期生(LOVE♡不知火フレア) 、音響機材'),
        MVtubersProfiles(id=205, vtuber_id=20, title='よく行う配信の種類', content='ゲーム(アクション・RPG！)、英語勉強、雑談、ASMR、晩酌雑談、朗読(歌)'),
        MVtubersProfiles(id=206, vtuber_id=20, title='Words', content='①口みたいな栗：団長が怒ったり悲しんだりしたときの口の形<br/>②ノエスタ：ノエルスタジオの略。主にこちらで配信してます！<br/>③テント：団長の自宅。田舎のスラム街にある。<br/>④ポップちゃん：団長が飼っているハムスター！家族です♡<br/>⑤あびゃびゃ：団長が食べてるときの音。'),
        MVtubersProfiles(id=207, vtuber_id=20, title='夢', content='大好きな三期生のみんなと一緒にライブする！'),
        MVtubersProfiles(id=208, vtuber_id=20, title='目標', content='ゆるふわに自分らしく活動して団員さんを幸せにする！日々頑張ってる団員さんの癒しや活力になれるよう活動してます！'),
        MVtubersProfiles(id=209, vtuber_id=20, title='メッセージ', content='生きてるだけでえらい！いつも頑張ってるキミを全力で(物理的に)支えたい。<br/>その為にもつよつよにならねば！日々ゲームや歌を修行中！<br/>白銀聖騎士団に入団して団長と一緒に良い汗を流しませんか ？！'),
        MVtubersProfiles(id=210, vtuber_id=21, title='誕生日', content='7月30日'),
        MVtubersProfiles(id=211, vtuber_id=21, title='初配信日', content='8月11日'),
        MVtubersProfiles(id=212, vtuber_id=21, title='身長', content='150cm'),
        MVtubersProfiles(id=213, vtuber_id=21, title='ユニット', content='ホロライブ3期生'),
        MVtubersProfiles(id=214, vtuber_id=21, title='イラストレーター', content='<a href="https://twitter.com/AkasaAi" target="_blank">あかさあい</a>'),
        MVtubersProfiles(id=215, vtuber_id=21, title='夢', content='海賊船を手に入れ、一味のキミたちと大海原へ出航し、最後には「マリンのお宝は…この景色とここにいるキミたちです」と言う予定。'),
        MVtubersProfiles(id=216, vtuber_id=21, title='ファンネーム', content='宝鐘の一味'),
        MVtubersProfiles(id=217, vtuber_id=21, title='ハッシュタグ', content='配信タグ：#マリン航海記<br/>ファンアート：#マリンのお宝'),
        MVtubersProfiles(id=218, vtuber_id=21, title='Message', content='エ◯ガキのみんな～♡イケナイ出航をしたいのであれば、マリン船長一択です！！<br/>エ◯ガキじゃないみんな～！！<br/>船長は、おもしろいと評判なのでエ◯ガキじゃなくても楽しめる可能性があります！<br/>人生経験豊富なわりに大体配信で話しつくしてもう新しいデッ キがありませんが随時入荷しているので安心してください！<br/>転職や失業する人へのアドバイスには自信があります！<br/>「実際船長のおかげで転職できた」という声を数多貰っていま す！<br/>コラボや企画なんかも積極的にするタイプなので是非、箱ごと 推してください！'),
        MVtubersProfiles(id=219, vtuber_id=21, title='趣味', content='かわいいものを見たり買ったり、エ◯本漁り、妄想、歌、セ◯ハラ'),
        MVtubersProfiles(id=220, vtuber_id=21, title='好きなもの', content='恋愛シミュレーション、ＳＴＧ、ホロメン、お姉ちゃん、一味のキミたち♡'),
        MVtubersProfiles(id=221, vtuber_id=21, title='特技', content='歯磨き、イラスト、モノマネ'),
        MVtubersProfiles(id=222, vtuber_id=22, title='誕生日', content='4月22日'),
        MVtubersProfiles(id=223, vtuber_id=22, title='初配信日', content='12月27日'),
        MVtubersProfiles(id=224, vtuber_id=22, title='身長', content='149cm'),
        MVtubersProfiles(id=225, vtuber_id=22, title='ユニット', content='ホロライブ4期生'),
        MVtubersProfiles(id=226, vtuber_id=22, title='イラストレーター', content='<a href="https://twitter.com/oshioshio_info" target="_blank">おしおしお</a>'),
        MVtubersProfiles(id=227, vtuber_id=22, title='ファンネーム', content='へい民'),
        MVtubersProfiles(id=228, vtuber_id=22, title='ハッシュタグ', content='配信タグ：#天界学園放送部<br/>ファンアート：#かなたーと'),
        MVtubersProfiles(id=229, vtuber_id=23, title='誕生日', content='6月6日'),
        MVtubersProfiles(id=230, vtuber_id=23, title='初配信日', content='12月29日'),
        MVtubersProfiles(id=231, vtuber_id=23, title='身長', content='151㎝'),
        MVtubersProfiles(id=232, vtuber_id=23, title='ユニット', content='ホロライブ4期生'),
        MVtubersProfiles(id=233, vtuber_id=23, title='イラストレーター<br>Live2Dデザイナー', content='<a href="https://twitter.com/fuumiisc" target="_blank">ふーみ</a><br/><a href="https://twitter.com/keffiy" target="_blank">けっふぃー</a>'),
        MVtubersProfiles(id=234, vtuber_id=23, title='夢', content='オリ曲オンリー武道館ライブ<br/>オリジナルアルバムをたくさん出したい<br/>ソロライブをする<br/>アニソン担当したい<br/>声優に挑戦したい<br/>ゲームやアニメのキャラクターにな りたい<br/>コラボカフェしたい<br/>フィギュア化したい<br/>親孝行する<br/>他にもいっぱいありすぎて書ききれない！'),
        MVtubersProfiles(id=235, vtuber_id=23, title='ファンネーム', content='わためいと'),
        MVtubersProfiles(id=236, vtuber_id=23, title='ハッシュタグ', content='配信タグ：#ドドドライブ<br/>ファンアート：#つのまきあーと<br/>切り抜き動画：わたわた動画'),
        MVtubersProfiles(id=237, vtuber_id=23, title='Words', content='WNF<br/>-毎週末開催している歌枠「わためぇ Night Fever!!」の略<br/>つのまきじゃんけん<br/>-わためのうた動画内で生まれたじゃんけんコーナー。<br/>ドドド<br/>-Twitterデビュー後２ツイート目に投稿された、わためが走り回っている足音から来ている。挨拶等で使われることがある。例：「こんばんドドド」<br/>わためNo.1<br/>-いつの間にか定着した、わためがNo.1だよという意味。たぶん。　※諸説あり今では、わためいととの合言葉みたいになっている。'),
        MVtubersProfiles(id=238, vtuber_id=23, title='Message', content='こんばんドドド！<br/>ホロライブ４期生の角巻わためです！<br/>歌うことが大好きで毎週ボイトレに通いながら、歌やゲームを中心に配信もしていまもしています！<br/>基本まったり癒し系な配信で、おやすみからおはようまでやっていることが多々ありが多々あります。<br/>睡眠導入にピッタリ！！！<br/>週末の夜には『わためぇ Night Fever!!』という名の歌枠をほぼ毎週開催しているのしているので、是非みんなで歌って踊りましょう！<br/>Dance Dance Dance！ Foooooooooooooo<br/>夢を叶えるため爆走中！！！<br/>一緒に武道館いこうね！！！！！'),
        MVtubersProfiles(id=239, vtuber_id=23, title='得意な配信/よくやる配信', content='歌枠、まったりゲーム'),
        MVtubersProfiles(id=240, vtuber_id=23, title='趣味', content='食う寝る遊ぶ歌う、トロコン'),
        MVtubersProfiles(id=241, vtuber_id=23, title='好きなもの', content='ポテチ（お菓子）、ゲーム、脇パイ、わためいと'),
        MVtubersProfiles(id=242, vtuber_id=23, title='特技', content='歌、8秒でリスポーンする、つのドリル、ガン◯マリフェイス等'),
        MVtubersProfiles(id=243, vtuber_id=23, title='推しマーク', content='🐏（角のある方の羊）'),
        MVtubersProfiles(id=244, vtuber_id=24, title='誕生日', content='8月8日'),
        MVtubersProfiles(id=245, vtuber_id=24, title='初配信日', content='1月3日'),
        MVtubersProfiles(id=246, vtuber_id=24, title='身長', content='150㎝'),
        MVtubersProfiles(id=247, vtuber_id=24, title='ユニット', content='ホロライブ4期生'),
        MVtubersProfiles(id=248, vtuber_id=24, title='イラストレーター', content='<a href="https://twitter.com/rurudo_" target="_blank">rurudo</a>'),
        MVtubersProfiles(id=249, vtuber_id=24, title='夢', content='ソロライブ！フルアルバム発売！海外でのライブ！'),
        MVtubersProfiles(id=250, vtuber_id=24, title='ファンネーム', content='常闇眷属'),
        MVtubersProfiles(id=251, vtuber_id=24, title='ハッシュタグ', content='配信タグ：#トワイライヴ<br/>ファンアート：#TOWART<br/>切り抜き：#CUTOWA'),
        MVtubersProfiles(id=252, vtuber_id=24, title='Words', content='こんやっぴー：はじまりの挨拶に使います！<br/>おつやっぴー：終わりの挨拶に使います！<br/>ビビ：トワの使い魔的なペットです。帽子になって監視されています。<br/>虎太郎：トワの飼っている足短猫です。愛称はこたーちです。<br/>TMT：Towa maji Tenshiの略らしいです。無許可<br/>TMD：Towa maji Devilの略。使え。<br/>YAB：YABAIとチャットに書こうとしたらミスった。意味はYABEと一緒<br/>Big草：海外ニキのLMAOってこれだよね？<br/>メンタル＆ゆっくり：トワが落ち着きます<br/>てんQ：みんないつもありがとう'),
        MVtubersProfiles(id=253, vtuber_id=24, title='好きなゲームジャンル', content='FPS、謎解き（脱出ゲームが好き！）'),
        MVtubersProfiles(id=254, vtuber_id=24, title='愛称', content='トワ様、トワしゃま'),
        MVtubersProfiles(id=255, vtuber_id=25, title='誕生日', content='10月10日'),
        MVtubersProfiles(id=256, vtuber_id=25, title='初配信日', content='1月4日'),
        MVtubersProfiles(id=257, vtuber_id=25, title='身長', content='140cm'),
        MVtubersProfiles(id=258, vtuber_id=25, title='ユニット', content='ホロライブ4期生'),
        MVtubersProfiles(id=259, vtuber_id=25, title='イラストレーター', content='<a href="https://twitter.com/kanzakihiro" target="_blank">かんざきひろ</a>'),
        MVtubersProfiles(id=260, vtuber_id=25, title='ファンネーム', content='ルーナイト'),
        MVtubersProfiles(id=261, vtuber_id=25, title='ハッシュタグ', content='配信タグ：#なのらいぶ<br/>ファンアート：#ルーナート'),
        MVtubersProfiles(id=262, vtuber_id=26, title='誕生日', content='11月15日'),
        MVtubersProfiles(id=263, vtuber_id=26, title='初配信日', content='8月12日'),
        MVtubersProfiles(id=264, vtuber_id=26, title='身長', content='158㎝'),
        MVtubersProfiles(id=265, vtuber_id=26, title='ユニット', content='ホロライブ5期生'),
        MVtubersProfiles(id=266, vtuber_id=26, title='イラストレーター', content='<a href="https://twitter.com/rin7914" target="_blank">リン☆ユ'),
        MVtubersProfiles(id=267, vtuber_id=26, title='夢/目標', content='ウ</a>'),
        MVtubersProfiles(id=268, vtuber_id=26, title='ファンネーム', content='・苦手なことにも挑戦していく！<br/>・ホロライブを盛り上げていくメンバーになりたい！<br/>・ホロライブの先輩と同じステージに、一緒に立ちたい！<br/>・チャンネル登録者100万人！雪民'),
        MVtubersProfiles(id=269, vtuber_id=26, title='ハッシュタグ', content='配信タグ：#らみらいぶ<br/>ファンアート：＃LamyArt'),
        MVtubersProfiles(id=270, vtuber_id=26, title='趣味・特技・好きなもの', content='趣味：配信、エゴサ<br/>特技：華道<br/>好きなアニメ：タイムリープ系アニメ<br/>泣けるアニメも好き'),
        MVtubersProfiles(id=271, vtuber_id=26, title='Message', content='ホロライブ5期生の雪花ラミィです！<br/>大好きなホロライブで、大好きなリスナーさんやホロメンとたくさん笑顔になりたいです⁽⁽ ◟(灬 ˊωˋ 灬)◞ ⁾⁾'),
        MVtubersProfiles(id=272, vtuber_id=26, title='得意な配信/よくやる配信', content='朝活：平日9時から毎日配信。内容は雑談やゲーム配信など。<br/>– 長時間配信になることが多く、長い時は5時間ほど配信している。<br/>夜活：週6日ほど22時～23時ごろから配信。<br/>– 内容は晩酌配信、ASMR、ゲーム配信など様々。'),
        MVtubersProfiles(id=273, vtuber_id=27, title='誕生日', content='3月2日'),
        MVtubersProfiles(id=274, vtuber_id=27, title='初配信日', content='8月13日'),
        MVtubersProfiles(id=275, vtuber_id=27, title='身長', content='159㎝'),
        MVtubersProfiles(id=276, vtuber_id=27, title='ユニット', content='ホロライブ5期生'),
        MVtubersProfiles(id=277, vtuber_id=27, title='イラストレーター', content='<a href="https://twitter.com/wanwangomigomi" target="_blank"> 西沢5㍉</a>'),
        MVtubersProfiles(id=278, vtuber_id=27, title='夢', content='全宇宙から認められるアイドルになること！<br/>全宇宙に旦那さんを作ること！'),
        MVtubersProfiles(id=279, vtuber_id=27, title='ファンネーム', content='ねっ子'),
        MVtubersProfiles(id=280, vtuber_id=27, title='Words', content='ねねアザラシ/NENESeal<br/>-ある日アザラシに似てるねって言われたことが始まり。ねねはアザラシ なの…！？<br/>ねねハズバンズコレクション<br/>-「結婚して下さい」のコメントに全て対応した結果、ものすごい数の旦 那さんをゲットすることに成功した。旦那さんたちが浮気しないように瓶詰めにしてコレクションしている。'),
        MVtubersProfiles(id=281, vtuber_id=27, title='Message', content='こんねね！！！！ねねでーす！！！見つけてくれてありがとう(･∞･っ)Э<br/>ねねがSUPER ULTRA ULTIMATEなアイドルになるまで、そばで成長を見守ってくれませんか？！みんなと一緒にいたらどんなことでもがんばれる気がする！！！！一緒に楽しいこと、いっぱい探しに行こう！！！！！'),
        MVtubersProfiles(id=282, vtuber_id=27, title='趣味', content='歌って踊ること！'),
        MVtubersProfiles(id=283, vtuber_id=27, title='好きなもの', content='ねっ子のみんな！'),
        MVtubersProfiles(id=284, vtuber_id=27, title='特技', content='イラストを描くこと！'),
        MVtubersProfiles(id=285, vtuber_id=28, title='誕生日', content='9月8日'),
        MVtubersProfiles(id=286, vtuber_id=28, title='初配信日', content='8月14日'),
        MVtubersProfiles(id=287, vtuber_id=28, title='身長', content='166㎝'),
        MVtubersProfiles(id=288, vtuber_id=28, title='ユニット', content='ホロライブ5期生'),
        MVtubersProfiles(id=289, vtuber_id=28, title='イラストレーター', content='<a href="https://twitter.com/ttomarii" target="_blank">トマリ</a>'),
        MVtubersProfiles(id=290, vtuber_id=28, title='夢', content='・ホロライブを教科書にのせる<br/>・新しい文化を作る'),
        MVtubersProfiles(id=291, vtuber_id=28, title='ファンネーム', content='SSRB'),
        MVtubersProfiles(id=292, vtuber_id=28, title='ハッシュタグ', content='配信タグ：#ぐうたらいぶ<br/>ファンアート：#ししらーと'),
        MVtubersProfiles(id=293, vtuber_id=28, title='Words', content='poi（ぽいっ）<br/>-獅白ぼたんがグレネードを投げる際に発する効果音。一緒にぽいぽいしよう。<br/>麺屋ぼたん<br/>-獅白ぼたんが店主を務めるラーメン屋。ちなみに企業名は「ししろフーズ」という。<br/>ショッピングカート<br/>-獅白ぼたんがレースのような場所で移動時に使う乗り物。なお中身はSSRB民（リスナー）という噂。<br/>点呼<br/>-スパチャなどで「最後まで見るで」のコメントに対し、不意打ちでいるかどうかの呼びかけをする行為。なお返事をしようがしまいが、点呼時にししろーランドのチケットをゲットできる可能性がある。<br/>ししろーランド<br/>-獅白ぼたんが運営する遊園地（という名の訓練施設）。名物は96Gもの重力負荷がかかるジェットコースター。チケットをゲットした際はぜひ乗ってみよう、飛ぶぞ。<br/>大葉、しいたけ<br/>-獅白ぼたんが家庭菜園で育てている。大葉は合法ハーブとしてタイバと呼ぶ時もある。最近は水草を育てているようだ。<br/>ししくん、ろんちゃん<br/>-獅白ぼたんの飼い猫。たまにチュール代を前借りされガチャや競馬に突っ込まれる。'),
        MVtubersProfiles(id=294, vtuber_id=28, title='Message', content='ららーいおん！獅白ぼたんです。普段はぐうたらしてるけど、やる時はやる子です。<br/>ゲームはFPSとか少し得意かな！歌の時は「ホワイトライオン」から「ほらいとらいおん」になると好評の様子。よかったらぜひ聞いてみてね！'),
        MVtubersProfiles(id=295, vtuber_id=28, title='得意な配信/よくやる配信', content='ゲーム配信が多め。'),
        MVtubersProfiles(id=296, vtuber_id=28, title='趣味', content='ゲーム'),
        MVtubersProfiles(id=297, vtuber_id=28, title='好きなもの', content='BOT撃ち、オレンジジュース、リスナーのみんな'),
        MVtubersProfiles(id=298, vtuber_id=28, title='特技', content='自作PC制作可能、制作した乗り物にリスナーを（無理矢理）のせる'),
        MVtubersProfiles(id=299, vtuber_id=29, title='誕生日', content='1月30日'),
        MVtubersProfiles(id=300, vtuber_id=29, title='初配信日', content='8月16日'),
        MVtubersProfiles(id=301, vtuber_id=29, title='身長', content='153㎝'),
        MVtubersProfiles(id=302, vtuber_id=29, title='ユニット', content='ホロライブ5期生'),
        MVtubersProfiles(id=303, vtuber_id=29, title='イラストレーター', content='<a href="https://twitter.com/itsuwa0815" target="_blank">こうましろ</a>'),
        MVtubersProfiles(id=304, vtuber_id=29, title='ファンネーム', content='座員'),
        MVtubersProfiles(id=305, vtuber_id=29, title='ハッシュタグ', content='配信タグ：#ポルカ公演中<br/>ファンアート：#絵まる'),
        MVtubersProfiles(id=306, vtuber_id=30, title='誕生日', content='5月25日'),
        MVtubersProfiles(id=307, vtuber_id=30, title='初配信日', content='11月26日'),
        MVtubersProfiles(id=308, vtuber_id=30, title='身長', content='139cm'),
        MVtubersProfiles(id=309, vtuber_id=30, title='ユニット', content='秘密結社holoX'),
        MVtubersProfiles(id=310, vtuber_id=30, title='イラストレーター', content='<a href="https://twitter.com/mishima_kurone" rel="noopener" target="_blank">三嶋くろね</a>'),
        MVtubersProfiles(id=311, vtuber_id=30, title='ファンネーム', content='ぷらすめいと'),
        MVtubersProfiles(id=312, vtuber_id=30, title='ハッシュタグ', content='配信タグ：#laplus_great<br/>アートタグ：#Laplus_Artdesu'),
        MVtubersProfiles(id=313, vtuber_id=30, title='得意な配信/よくやる配信', content='　'),
        MVtubersProfiles(id=314, vtuber_id=31, title='誕生日', content='6月11日'),
        MVtubersProfiles(id=315, vtuber_id=31, title='初配信日', content='11月27日'),
        MVtubersProfiles(id=316, vtuber_id=31, title='身長', content='161㎝'),
        MVtubersProfiles(id=317, vtuber_id=31, title='ユニット', content='秘密結社holoX'),
        MVtubersProfiles(id=318, vtuber_id=31, title='イラストレーター', content='<a href="https://twitter.com/kakage0904" target="_blank">かかげ</a>'),
        MVtubersProfiles(id=319, vtuber_id=31, title='ファンネーム', content='ルイ友'),
        MVtubersProfiles(id=320, vtuber_id=31, title='夢', content='安心して推せるバラエティーアイドル！！<br/>笑顔と温かい気持ちを届けたい！！！'),
        MVtubersProfiles(id=321, vtuber_id=31, title='ハッシュタグ', content='配信タグ：#たかねの見物<br/>ファンアートタグ：#Luillust'),
        MVtubersProfiles(id=322, vtuber_id=31, title='Words', content='「まったかね～？」：鷹嶺ルイ特有の挨拶<br/>「おつルイルイ」：鷹嶺ルイ特有の締めの挨拶<br/>「○○したかね？」：疑問形の活用<br/>「鷹まってきた～！」：「高まってきた～！」という意味<br/>「PON」：ポンコツなこと<br/>「コッ☆」：イケボで言いことを言った時の締めの言葉<br/>「水こぼさないでね」：よく水をこぼしてキーボードを壊す<br/> 「K Time」：彼女は賢者になったようだ<br/>「寒／え？／は？／暖房きった？」：ルイが寒いギャグをいったこと'),
        MVtubersProfiles(id=323, vtuber_id=31, title='Message', content='夢のためなら努力は惜しまない！<br/>みんなの笑顔のためなら頑張れる！<br/>ファン（ルイ友）のみんながいるから、私はこれからも走り続けられるよ。<br/>たまにアホなことしたり突っ走っちゃうけど、たくさんの愛でみんなに元気を届けるから応援してくれると嬉しいです！<br/>寝むれない日のお供やごはんのお供に鷹嶺ルイ、いかがですか？<br/>   あなたの毎日にとってなくてはならない存在になりたいけど無理せず推し活を楽しんでね！Luv U！'),
        MVtubersProfiles(id=324, vtuber_id=31, title='得意な配信/よくやる配信', content='ゲーム実況、歌配信、企画、雑談'),
        MVtubersProfiles(id=325, vtuber_id=31, title='特技', content='地獄企画を考える、料理、ルイ友監視、ホークアイ'),
        MVtubersProfiles(id=326, vtuber_id=31, title='趣味', content='アイドルを推すこと、香りを集めること、エゴサ、料理'),
        MVtubersProfiles(id=327, vtuber_id=31, title='好きなもの', content='漬物、激辛、アスパラガスビスケット、歌、ゲーム、ホロライブ、ルイ友'),
        MVtubersProfiles(id=328, vtuber_id=31, title='推しマーク', content='🥀（まだ高嶺の花と言えないけどいつか自信をもって上を向きたいという意味がある）'),
        MVtubersProfiles(id=329, vtuber_id=32, title='誕生日', content='3月15日'),
        MVtubersProfiles(id=330, vtuber_id=32, title='初配信日', content='11月28日'),
        MVtubersProfiles(id=331, vtuber_id=32, title='身長', content='153㎝'),
        MVtubersProfiles(id=332, vtuber_id=32, title='ユニット', content='秘密結社holoX'),
        MVtubersProfiles(id=333, vtuber_id=32, title='イラストレーター', content='<a href="https://twitter.com/momoco_haru" target="_blank">ももこ</a>'),
        MVtubersProfiles(id=334, vtuber_id=32, title='ファンネーム', content='こよりの助手くん'),
        MVtubersProfiles(id=335, vtuber_id=32, title='夢', content='すべての夢を叶えること！'),
        MVtubersProfiles(id=336, vtuber_id=32, title='ハッシュタグ', content='配信タグ：#こより実験中<br/>ファンアートタグ：#こよりすけっち'),
        MVtubersProfiles(id=337, vtuber_id=32, title='Words', content='「こんこよ～！」：あいさつ<br/>「コヨリニウム」：こよりの配信を観ることで摂取できる栄養素<br/>   「冷こよ」：冷静なこより<br/>「ココロ」：白衣のポケットに入っている相棒のロボコヨーテ第1号<br/>「こよ色」：ピンク色のこと'),
        MVtubersProfiles(id=338, vtuber_id=32, title='Message', content='こんこよ～！holoXの頭脳、博衣こよりだよ～！初見古参関係なく、いつ 来ても笑顔になれる配信をモットーに活動しています！いつでも会いに来てねっ(ᐡ •͈ ·̫ •͈ ᐡ)'),
        MVtubersProfiles(id=339, vtuber_id=32, title='よくやる配信', content='ゲーム実況中心に、歌枠、ASMR、雑談など幅広く活動しています！ 悲鳴 やリアクションに定評があるようです？<br/>毎週(火)(金)朝7:00～ホロライブ情報番組「朝こよ！」放送中！'),
        MVtubersProfiles(id=340, vtuber_id=32, title='特技', content='滑舌、クレーンゲーム、タイピング'),
        MVtubersProfiles(id=341, vtuber_id=32, title='趣味', content='歌って踊ること、演じること、謎解き、人狼、ボードゲーム、麻雀'),
        MVtubersProfiles(id=342, vtuber_id=32, title='好きなもの', content='ゲーム、マヨネーズ、日本酒、助手くん'),
        MVtubersProfiles(id=343, vtuber_id=32, title='推しマーク', content='🧪'),
        MVtubersProfiles(id=344, vtuber_id=33, title='誕生日', content='5月18日'),
        MVtubersProfiles(id=345, vtuber_id=33, title='初配信日', content='11月29日'),
        MVtubersProfiles(id=346, vtuber_id=33, title='身長', content='148cm'),
        MVtubersProfiles(id=347, vtuber_id=33, title='ユニット', content='秘密結社holoX'),
        MVtubersProfiles(id=348, vtuber_id=33, title='イラストレーター', content='<a href="https://twitter.com/parsley_f?s=21" rel="noopener" target="_blank">パセリ</a>'),
        MVtubersProfiles(id=349, vtuber_id=33, title='ファンネーム', content='飼育員'),
        MVtubersProfiles(id=350, vtuber_id=33, title='夢', content='・大きな舞台でソロライブをする事<br/>・フィギュア化する事<br/>・水族館とコラボをする事'),
        MVtubersProfiles(id=351, vtuber_id=33, title='ハッシュタグ', content='配信タグ：#またまたさかまた<br/>ファンアートタグ：#さかまた飼育日記'),
        MVtubersProfiles(id=352, vtuber_id=33, title='Words', content='【はじめの挨拶】<br/>「ばっくばっくばく～ん」<br/>「いただきます」<br/>【終わりの挨拶】<br/>「ごちそうさまでした」<br/>【待機中のおさかな】<br/>＜＞＜<br/>【君】<br/>飼育員さん'),
        MVtubersProfiles(id=353, vtuber_id=33, title='好きなもの', content='・めんたいこ<br/>・ショートケーキ<br/>・音楽<br/>・睡眠<br/>・テーマパーク'),
        MVtubersProfiles(id=354, vtuber_id=33, title='推しマーク', content='🎣'),
        MVtubersProfiles(id=355, vtuber_id=34, title='誕生日', content='6月18日'),
        MVtubersProfiles(id=356, vtuber_id=34, title='初配信日', content='11月30日'),
        MVtubersProfiles(id=357, vtuber_id=34, title='身長', content='156cm'),
        MVtubersProfiles(id=358, vtuber_id=34, title='ユニット', content='秘密結社holoX'),
        MVtubersProfiles(id=359, vtuber_id=34, title='イラストレーター', content='<a href="https://twitter.com/bouzumi_?s=21" rel="noopener" target="_blank">うみぼうず</a>'),
        MVtubersProfiles(id=360, vtuber_id=34, title='ファンネーム', content='かざま隊'),
        MVtubersProfiles(id=361, vtuber_id=34, title='ハッシュタグ', content='配信タグ：#かざま修行中<br/>ファンアートタグ：#いろはにも絵を'),
        MVtubersProfiles(id=362, vtuber_id=35, title='誕生日', content='2月27日'),
        MVtubersProfiles(id=363, vtuber_id=35, title='初配信日', content='9月9日'),
        MVtubersProfiles(id=364, vtuber_id=35, title='身長', content='171cm'),
        MVtubersProfiles(id=365, vtuber_id=35, title='ユニット', content='ReGLOSS'),
        MVtubersProfiles(id=366, vtuber_id=35, title='イラストレーター', content='<a href="https://twitter.com/omu001" target="_blank">むっしゅ</a>'),
        MVtubersProfiles(id=367, vtuber_id=36, title='誕生日', content='4月20日'),
        MVtubersProfiles(id=368, vtuber_id=36, title='初配信日', content='9月9日'),
        MVtubersProfiles(id=369, vtuber_id=36, title='身長', content='153cm'),
        MVtubersProfiles(id=370, vtuber_id=36, title='ユニット', content='ReGLOSS'),
        MVtubersProfiles(id=371, vtuber_id=36, title='イラストレーター', content='<a href="https://twitter.com/gcmzi" target="_blank">gomzi</a>'),
        MVtubersProfiles(id=372, vtuber_id=37, title='誕生日', content='5月12日'),
        MVtubersProfiles(id=373, vtuber_id=37, title='初配信日', content='9月9日'),
        MVtubersProfiles(id=374, vtuber_id=37, title='身長', content='162cm'),
        MVtubersProfiles(id=375, vtuber_id=37, title='ユニット', content='ReGLOSS'),
        MVtubersProfiles(id=376, vtuber_id=37, title='イラストレーター', content='<a href="https://twitter.com/mmnummn" target="_blank">なかむら</a>'),
        MVtubersProfiles(id=377, vtuber_id=38, title='誕生日', content='2月4日'),
        MVtubersProfiles(id=378, vtuber_id=38, title='初配信日', content='9月10日'),
        MVtubersProfiles(id=379, vtuber_id=38, title='身長', content='159cm'),
        MVtubersProfiles(id=380, vtuber_id=38, title='ユニット', content='ReGLOSS'),
        MVtubersProfiles(id=381, vtuber_id=38, title='イラストレーター', content='<a href="https://twitter.com/kaoming775" target="_blank">カオミン</a>'),
        MVtubersProfiles(id=382, vtuber_id=39, title='誕生日', content='6月7日'),
        MVtubersProfiles(id=383, vtuber_id=39, title='初配信日', content='9月10日'),
        MVtubersProfiles(id=384, vtuber_id=39, title='身長', content='155cm'),
        MVtubersProfiles(id=385, vtuber_id=39, title='ユニット', content='ReGLOSS'),
        MVtubersProfiles(id=386, vtuber_id=39, title='イラストレーター', content='<a href="https://twitter.com/atikix" target="_blank">Aちき</a>'),
        MVtubersProfiles(id=387, vtuber_id=40, title='誕生日', content='2月28日'),
        MVtubersProfiles(id=388, vtuber_id=40, title='初出演日', content='2月28日'),
        MVtubersProfiles(id=389, vtuber_id=40, title='身長', content='157.1cm'),
        MVtubersProfiles(id=390, vtuber_id=40, title='ユニット', content='事務所スタッフ'),
        MVtubersProfiles(id=391, vtuber_id=40, title='イラストレーター', content='<a href="https://twitter.com/ordan" target="_blank">おるだん</a>'),
        MVtubersProfiles(id=392, vtuber_id=40, title='夢', content='ホロライブを世界一のVTuberアイドル事務所にする<br/>後輩「春先のどか」と2人で、VTuber界イチの先輩後輩コンビになる<br/>仕事系ドキュメンタリー番組に密着される'),
        MVtubersProfiles(id=393, vtuber_id=40, title='ハッシュタグ', content='ファンアート：#絵ーちゃん<br/>定期配信：#ホロのこしかけ'),
        MVtubersProfiles(id=394, vtuber_id=40, title='Words', content='月曜日<br/>汚い悲鳴<br/>ホロぐらのモブ'),
        MVtubersProfiles(id=395, vtuber_id=40, title='趣味', content='ホロライブメンバーの配信・ツイート確認<br/>英語の勉強<br/>音楽/DJ'),
        MVtubersProfiles(id=396, vtuber_id=40, title='好きなもの', content='激辛料理（特にカレー）<br/>エナジードリンク'),
        MVtubersProfiles(id=397, vtuber_id=41, title='誕生日', content='5月7日'),
        MVtubersProfiles(id=398, vtuber_id=41, title='初出演日', content='4月1日'),
        MVtubersProfiles(id=399, vtuber_id=41, title='身長', content='154cm'),
        MVtubersProfiles(id=400, vtuber_id=41, title='ユニット', content='事務所スタッフ'),
        MVtubersProfiles(id=401, vtuber_id=41, title='イラストレーター', content='<a href="https://twitter.com/ordan" target="_blank">おるだん</a>'),
        MVtubersProfiles(id=402, vtuber_id=41, title='夢', content='えーちゃんさんのような敏腕スタッフになって、お仕事をたくさんこなせるようになりたいです！<br/>日本全国や海外のファンの皆さんが集まるイベントで、ナレーションを担当してみたいです！'),
        MVtubersProfiles(id=403, vtuber_id=41, title='ハッシュタグ', content='ファンアート：#のどかあーと'),
        MVtubersProfiles(id=404, vtuber_id=41, title='趣味', content='タレントの皆さんの配信を観ること<br/>歌をうたうこと<br/>クトゥルフ神話TRPG・マーダーミステリー'),
        MVtubersProfiles(id=405, vtuber_id=41, title='好きなもの', content='チュロス'),
        MVtubersProfiles(id=406, vtuber_id=41, title='特技', content='きれいな画像を作ること'),
    ])

    # お気に入り動画タグ情報
    MFavoriteVideoTags.objects.bulk_create([
        MFavoriteVideoTags(
            id=1,
            tag='game',
            tag_name='ゲーム'
        ),
        MFavoriteVideoTags(
            id=2,
            tag='singing',
            tag_name='歌唱'
        ),
        MFavoriteVideoTags(
            id=3,
            tag='chat',
            tag_name='雑談'
        ),
        MFavoriteVideoTags(
            id=4,
            tag='cooking',
            tag_name='料理'
        ),
        MFavoriteVideoTags(
            id=5,
            tag='asmr',
            tag_name='ASMR'
        ),
        MFavoriteVideoTags(
            id=6,
            tag='collaboration',
            tag_name='コラボ'
        ),
        MFavoriteVideoTags(
            id=7,
            tag='cover',
            tag_name='歌ってみた'
        ),
        MFavoriteVideoTags(
            id=8,
            tag='funny',
            tag_name='面白い'
        ),
        MFavoriteVideoTags(
            id=9,
            tag='touching',
            tag_name='感動'
        ),
        MFavoriteVideoTags(
            id=10,
            tag='cute',
            tag_name='可愛い'
        ),
        MFavoriteVideoTags(
            id=11,
            tag='cool',
            tag_name='かっこいい'
        ),
        MFavoriteVideoTags(
            id=12,
            tag='clip',
            tag_name='切り抜き'
        ),
        MFavoriteVideoTags(
            id=13,
            tag='official',
            tag_name='公式'
        ),
        MFavoriteVideoTags(
            id=14,
            tag='gen-0',
            tag_name='0期生'
        ),
        MFavoriteVideoTags(
            id=15,
            tag='1stgen',
            tag_name='1期生'
        ),
        MFavoriteVideoTags(
            id=16,
            tag='gen-2',
            tag_name='2期生'
        ),
        MFavoriteVideoTags(
            id=17,
            tag='gamers',
            tag_name='ホロライブゲーマーズ'
        ),
        MFavoriteVideoTags(
            id=18,
            tag='gen-3',
            tag_name='3期生'
        ),
        MFavoriteVideoTags(
            id=19,
            tag='gen-4',
            tag_name='4期生'
        ),
        MFavoriteVideoTags(
            id=20,
            tag='gen-5',
            tag_name='5期生'
        ),
        MFavoriteVideoTags(
            id=21,
            tag='holox',
            tag_name='秘密結社holoX'
        ),
        MFavoriteVideoTags(
            id=22,
            tag='regloss',
            tag_name='ReGLOSS'
        ),
        MFavoriteVideoTags(
            id=23,
            tag='tag_office-staff',
            tag_name='事務所スタッフ'
        ),
    ])

# スクリプトを実行するための条件を設定
if __name__ == '__main__':
    add_data()
